# **Cleaning Notebook**

**SET UP**

In [ ]:
from google.colab import drive

drive.mount("/content/drive")

MessageError: Error: credential propagation was unsuccessful

In [ ]:
from pathlib import Path
import pandas as pd
import re
!pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
PROJECT_FOLDER = (
    Path("/content/drive/MyDrive")
    / "AL-VOTE DATA FOLDER"
)

RAW_2020 = PROJECT_FOLDER / "01_Raw_Data" / "2020"
RAW_2024 = PROJECT_FOLDER / "01_Raw_Data" / "2024"

CLEAN_2020 = PROJECT_FOLDER / "02_Cleaned_Data" / "2020"
CLEAN_2024 = PROJECT_FOLDER / "02_Cleaned_Data" / "2024"
CLEAN_COMBINED = PROJECT_FOLDER / "02_Cleaned_Data" / "Combined"

CLEAN_2020.mkdir(parents=True, exist_ok=True)
CLEAN_2024.mkdir(parents=True, exist_ok=True)
CLEAN_COMBINED.mkdir(parents=True, exist_ok=True)

print("Project folder:", PROJECT_FOLDER)
print("Folders successfully connected.")

NameError: name 'Path' is not defined

In [ ]:
print("2020 raw files:\n")

for file in sorted(RAW_2020.iterdir()):
    print(file.name)

2020 raw files:

2020-General-Autauga.xls
2020-General-Bibb.xls
2020-General-Blount.xls
2020-General-Calhoun.xls
2020-General-Chambers.xls
2020-General-Cherokee.xls
2020-General-Chilton.xls
2020-General-Clay.xls
2020-General-Cleburne.xls
2020-General-Coffee.xls
2020-General-Colbert.xls
2020-General-Coosa.xls
2020-General-Covington.xls
2020-General-Cullman.xls
2020-General-Dale.xls
2020-General-DeKalb.xls
2020-General-Elmore.xls
2020-General-Etowah.xls
2020-General-Fayette.xls
2020-General-Franklin.xls
2020-General-Geneva.xls
2020-General-Henry.xls
2020-General-Houston.xls
2020-General-Jackson.xls
2020-General-Jefferson.xls
2020-General-Lamar.xls
2020-General-Lauderdale.xls
2020-General-Lawrence.xls
2020-General-Lee.xls
2020-General-Limestone.xls
2020-General-Madison.xls
2020-General-Marion.xls
2020-General-Marshall.xls
2020-General-Morgan.xls
2020-General-Pickens.xls
2020-General-Randolph.xls
2020-General-Shelby.xls
2020-General-StClair.xls
2020-General-Talladega.xls
2020-General-Tallapoosa.xls
2020-General-Tuscaloosa.xls
2020-General-Walker.xls
2020-General-Winston.xls
2020_Age.csv
2020_Gender.csv
2020_Race.csv
ALVR-2020.xls
al_cvap_2020_cnty.csv

In [ ]:
print("2024 raw files:\n")

for file in sorted(RAW_2024.iterdir()):
    print(file.name)

2024 raw files:

2024-General-Autauga.xls
2024-General-Bibb.xls
2024-General-Blount.xls
2024-General-Calhoun.xls
2024-General-Chambers.xls
2024-General-Cherokee.xls
2024-General-Chilton.xls
2024-General-Clay.xls
2024-General-Cleburne.xls
2024-General-Coffee.xls
2024-General-Colbert.xls
2024-General-Coosa.xls
2024-General-Covington.xls
2024-General-Cullman.xls
2024-General-Dale.xls
2024-General-DeKalb.xls
2024-General-Elmore.xls
2024-General-Etowah.xls
2024-General-Fayette.xls
2024-General-Franklin.xls
2024-General-Geneva.xls
2024-General-Henry.xls
2024-General-Houston.xls
2024-General-Jackson.xls
2024-General-Jefferson.xls
2024-General-Lamar.xls
2024-General-Lauderdale.xls
2024-General-Lawrence.xls
2024-General-Lee.xls
2024-General-Limestone.xls
2024-General-Madison.xls
2024-General-Marion.xls
2024-General-Marshall.xls
2024-General-Morgan.xls
2024-General-Pickens.xls
2024-General-Randolph.xls
2024-General-Shelby.xls
2024-General-StClair.xls
2024-General-Talladega.xls
2024-General-Tallapoosa.xls
2024-General-Tuscaloosa.xls
2024-General-Walker.xls
2024-General-Winston.xls
2024_Age.csv
2024_Gender.csv
2024_Race.csv
ALVR-2024.xlsx
al_cvap_2024_cnty.csv

In [ ]:
age_2020_raw = pd.read_csv(
    RAW_2020 / "2020_Age.csv"
)

age_2020_raw.head()

,County,Total Ballots Cast,Age 18-29,Age 30-39,Age 40-49,Age 50-59,Age 60-69,Age 70-79,Age 80-89,Age 90-99,Age 100+
0,AUTAUGA,"27,681","3,701","4,051","4,619","5,512","5,047","3,277","1,321",153,0
1,BALDWIN,"110,922","10,689","13,025","15,928","20,071","23,641","19,520","7,024","1,002",22
2,BARBOUR,"10,551","1,092","1,218","1,351","1,964","2,325","1,876",631,90,4
3,BIBB,"8,797","1,320","1,231","1,393","1,772","1,551","1,069",399,58,4
4,BLOUNT,"27,694","3,774","3,705","4,237","5,269","5,290","3,852","1,361",191,15

In [ ]:
print(age_2020_raw.columns.tolist())

['County', 'Total Ballots Cast', 'Age 18-29', 'Age 30-39', 'Age 40-49', 'Age 50-59', 'Age 60-69', 'Age 70-79', 'Age 80-89', 'Age 90-99', 'Age 100+']



---

# **DEMOGRAPHIC DATA: 2020 AGE**

**#1: Loading File**

In [ ]:
import pandas as pd

age_2020_raw = pd.read_csv(
    RAW_2020 / "2020_Age.csv"
)

print("Raw shape:", age_2020_raw.shape)
age_2020_raw.head()

Raw shape: (68, 11)

,County,Total Ballots Cast,Age 18-29,Age 30-39,Age 40-49,Age 50-59,Age 60-69,Age 70-79,Age 80-89,Age 90-99,Age 100+
0,AUTAUGA,"27,681","3,701","4,051","4,619","5,512","5,047","3,277","1,321",153,0
1,BALDWIN,"110,922","10,689","13,025","15,928","20,071","23,641","19,520","7,024","1,002",22
2,BARBOUR,"10,551","1,092","1,218","1,351","1,964","2,325","1,876",631,90,4
3,BIBB,"8,797","1,320","1,231","1,393","1,772","1,551","1,069",399,58,4
4,BLOUNT,"27,694","3,774","3,705","4,237","5,269","5,290","3,852","1,361",191,15



---

**#2: County List**

In [ ]:
PROJECT_COUNTIES = [
    "Autauga",
    "Bibb",
    "Blount",
    "Calhoun",
    "Chambers",
    "Cherokee",
    "Chilton",
    "Clay",
    "Cleburne",
    "Coffee",
    "Colbert",
    "Coosa",
    "Covington",
    "Cullman",
    "Dale",
    "DeKalb",
    "Elmore",
    "Etowah",
    "Fayette",
    "Franklin",
    "Geneva",
    "Henry",
    "Houston",
    "Jackson",
    "Jefferson",
    "Lamar",
    "Lauderdale",
    "Lawrence",
    "Lee",
    "Limestone",
    "Madison",
    "Marion",
    "Marshall",
    "Morgan",
    "Pickens",
    "Randolph",
    "Shelby",
    "St. Clair",
    "Talladega",
    "Tallapoosa",
    "Tuscaloosa",
    "Walker",
    "Winston",
]



---

**#3: Needed Function**


*   Removes commas/spaces


*   Converts values to whole numbers
*   Blank values become missing values

In [ ]:
def clean_numeric_column(series):
    cleaned = (
        series.astype("string")
        .str.strip()
        .str.replace(",", "", regex=False)
        .str.replace(r"\s+", "", regex=True)
        .replace({
            "": pd.NA,
            "NA": pd.NA,
            "N/A": pd.NA,
            "nan": pd.NA,
        })
    )

    return pd.to_numeric(
        cleaned,
        errors="coerce"
    ).astype("Int64")



---

**#4: Cleaning**

*   Renames columns to be easier for SQL
* Cleans county names

*   Removes the statwide totals row

*   Adds year as the first column


*   Identifies all numeric columns
*   Removes commas and converts numeric columns to integers


*   Keeps only the 43 relevant counties
*   Sorts alphabetically

In [ ]:
age_2020 = age_2020_raw.copy()

age_2020 = age_2020.rename(
    columns={
        "County": "county_name",
        "Total Ballots Cast": "total_participants",
        "Age 18-29": "age_18_29",
        "Age 30-39": "age_30_39",
        "Age 40-49": "age_40_49",
        "Age 50-59": "age_50_59",
        "Age 60-69": "age_60_69",
        "Age 70-79": "age_70_79",
        "Age 80-89": "age_80_89",
        "Age 90-99": "age_90_99",
        "Age 100+": "age_100_plus",
    }
)

age_2020["county_name"] = (
    age_2020["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)
    .str.lower()
    .str.title()
)

age_2020["county_name"] = age_2020["county_name"].replace(
    {
        "Dekalb": "DeKalb",
        "St Clair": "St. Clair",
    }
)

age_2020 = age_2020[
    age_2020["county_name"].str.upper() != "TOTALS"
].copy()

age_2020.insert(0, "year", 2020)

numeric_columns = [
    "total_participants",
    "age_18_29",
    "age_30_39",
    "age_40_49",
    "age_50_59",
    "age_60_69",
    "age_70_79",
    "age_80_89",
    "age_90_99",
    "age_100_plus",
]

for column in numeric_columns:
    age_2020[column] = clean_numeric_column(
        age_2020[column]
    )

age_2020 = age_2020[
    age_2020["county_name"].isin(PROJECT_COUNTIES)
].copy()

age_2020 = age_2020.sort_values(
    "county_name"
).reset_index(drop=True)

print("Cleaned shape:", age_2020.shape)

age_2020.head()

Cleaned shape: (43, 12)

,year,county_name,total_participants,age_18_29,age_30_39,age_40_49,age_50_59,age_60_69,age_70_79,age_80_89,age_90_99,age_100_plus
0,2020,Autauga,27681,3701,4051,4619,5512,5047,3277,1321,153,0
1,2020,Bibb,8797,1320,1231,1393,1772,1551,1069,399,58,4
2,2020,Blount,27694,3774,3705,4237,5269,5290,3852,1361,191,15
3,2020,Calhoun,51304,6473,6703,7590,9407,10488,7452,2749,429,13
4,2020,Chambers,15481,1813,1842,2191,2942,3283,2425,817,161,7



---

**#5: Checking**
 if we have data for all 43 counties

*   Data for all 43 counties
*   Duplicates or missing values


*   If age groups equal total population

In [ ]:
counties_found = set(age_2020["county_name"])
counties_expected = set(PROJECT_COUNTIES)

missing_counties = sorted(
    counties_expected - counties_found
)

unexpected_counties = sorted(
    counties_found - counties_expected
)

print("Missing counties:", missing_counties)
print("Unexpected counties:", unexpected_counties)

Missing counties: []
Unexpected counties: []

In [ ]:
duplicate_rows = age_2020[
    age_2020.duplicated(
        subset=["year", "county_name"],
        keep=False
    )
]

print("Number of duplicate rows:", len(duplicate_rows))

duplicate_rows

Number of duplicate rows: 0

Empty DataFrame
Columns: [year, county_name, total_participants, age_18_29, age_30_39, age_40_49, age_50_59, age_60_69, age_70_79, age_80_89, age_90_99, age_100_plus]
Index: []

In [ ]:
missing_values = age_2020.isna().sum()

print(missing_values)

year                  0
county_name           0
total_participants    0
age_18_29             0
age_30_39             0
age_40_49             0
age_50_59             0
age_60_69             0
age_70_79             0
age_80_89             0
age_90_99             0
age_100_plus          0
dtype: int64

In [ ]:
age_group_columns = [
    "age_18_29",
    "age_30_39",
    "age_40_49",
    "age_50_59",
    "age_60_69",
    "age_70_79",
    "age_80_89",
    "age_90_99",
    "age_100_plus",
]

age_2020["calculated_age_total"] = (
    age_2020[age_group_columns].sum(axis=1)
)

age_2020["age_total_difference"] = (
    age_2020["calculated_age_total"]
    - age_2020["total_participants"]
)

age_discrepancies = age_2020.loc[
    age_2020["age_total_difference"] != 0,
    [
        "county_name",
        "total_participants",
        "calculated_age_total",
        "age_total_difference",
    ]
]

print(
    "Counties with age-total discrepancies:",
    len(age_discrepancies)
)

age_discrepancies

Counties with age-total discrepancies: 0

Empty DataFrame
Columns: [county_name, total_participants, calculated_age_total, age_total_difference]
Index: []

In [ ]:
age_2020 = age_2020.drop(
    columns=[
        "calculated_age_total",
        "age_total_difference",
    ]
)

print(age_2020.columns.tolist())

['year', 'county_name', 'total_participants', 'age_18_29', 'age_30_39', 'age_40_49', 'age_50_59', 'age_60_69', 'age_70_79', 'age_80_89', 'age_90_99', 'age_100_plus']



---

**#6: Save CSV and Final Check**

In [ ]:
age_2020_output = (
    CLEAN_2020
    / "age_participation_2020_clean.csv"
)

age_2020.to_csv(
    age_2020_output,
    index=False,
    encoding="utf-8"
)

print("Saved cleaned file to:")
print(age_2020_output)

Saved cleaned file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2020/age_participation_2020_clean.csv

In [ ]:
age_2020_check = pd.read_csv(age_2020_output)

print("Saved file shape:", age_2020_check.shape)
print(age_2020_check.dtypes)

age_2020_check.head()

Saved file shape: (43, 12)
year                   int64
county_name           object
total_participants     int64
age_18_29              int64
age_30_39              int64
age_40_49              int64
age_50_59              int64
age_60_69              int64
age_70_79              int64
age_80_89              int64
age_90_99              int64
age_100_plus           int64
dtype: object

,year,county_name,total_participants,age_18_29,age_30_39,age_40_49,age_50_59,age_60_69,age_70_79,age_80_89,age_90_99,age_100_plus
0,2020,Autauga,27681,3701,4051,4619,5512,5047,3277,1321,153,0
1,2020,Bibb,8797,1320,1231,1393,1772,1551,1069,399,58,4
2,2020,Blount,27694,3774,3705,4237,5269,5290,3852,1361,191,15
3,2020,Calhoun,51304,6473,6703,7590,9407,10488,7452,2749,429,13
4,2020,Chambers,15481,1813,1842,2191,2942,3283,2425,817,161,7



---

# **DEMOGRAPHIC DATA: 2024 AGE**

In [ ]:
age_2024_raw = pd.read_csv(
    RAW_2024 / "2024_Age.csv"
)

print("Raw shape:", age_2024_raw.shape)
age_2024_raw.head()

Raw shape: (69, 11)

,County,Total Ballots Cast,Age 18-29,Age 30-39,Age 40-49,Age 50-59,Age 60-69,Age 70-79,Age 80-89,Age 90-99,Age 100+
0,2024 General Election Participation by Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AUTAUGA,"28,401","3,600","3,991","4,631","5,223","5,428","3,710","1,584",231,3.0
2,BALDWIN,"122,501","11,800","1 3,847","1 7,274","2 0,669","2 5,839","2 2,880","8,940","1,218",34.0
3,BARBOUR,"9,901",970,949,"1,206","1,670","2,231","1,989",767,119,0.0
4,BIBB,"9,283","1,275","1,211","1,323","1,737","1,787","1,355",527,66,2.0



---

In [ ]:
age_2024 = age_2024_raw.copy()

age_2024 = age_2024.rename(
    columns={
        "County": "county_name",
        "Total Ballots Cast": "total_participants",
        "Age 18-29": "age_18_29",
        "Age 30-39": "age_30_39",
        "Age 40-49": "age_40_49",
        "Age 50-59": "age_50_59",
        "Age 60-69": "age_60_69",
        "Age 70-79": "age_70_79",
        "Age 80-89": "age_80_89",
        "Age 90-99": "age_90_99",
        "Age 100+": "age_100_plus",
    }
)

age_2024["county_name"] = (
    age_2024["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)
    .str.lower()
    .str.title()
)

age_2024["county_name"] = age_2024["county_name"].replace(
    {
        "Dekalb": "DeKalb",
        "St Clair": "St. Clair",
    }
)

age_2024 = age_2024[
    age_2024["county_name"].str.upper() != "TOTALS"
].copy()

age_2024.insert(0, "year", 2024)

age_numeric_columns = [
    "total_participants",
    "age_18_29",
    "age_30_39",
    "age_40_49",
    "age_50_59",
    "age_60_69",
    "age_70_79",
    "age_80_89",
    "age_90_99",
    "age_100_plus",
]

for column in age_numeric_columns:
    age_2024[column] = clean_numeric_column(
        age_2024[column]
    )

age_2024 = age_2024[
    age_2024["county_name"].isin(PROJECT_COUNTIES)
].copy()

age_2024 = age_2024.sort_values(
    "county_name"
).reset_index(drop=True)

print("Cleaned shape:", age_2024.shape)

age_2024.head()

Cleaned shape: (43, 12)

,year,county_name,total_participants,age_18_29,age_30_39,age_40_49,age_50_59,age_60_69,age_70_79,age_80_89,age_90_99,age_100_plus
0,2024,Autauga,28401,3600,3991,4631,5223,5428,3710,1584,231,3
1,2024,Bibb,9283,1275,1211,1323,1737,1787,1355,527,66,2
2,2024,Blount,28255,3914,3800,4195,5005,5324,4222,1572,216,7
3,2024,Calhoun,48732,5991,5948,7119,8161,9857,8205,2958,477,16
4,2024,Chambers,13687,1508,1573,1729,2478,2902,2466,874,154,3



---

In [ ]:
print("Missing values after numeric cleaning:")

print(
    age_2024[
        age_numeric_columns
    ].isna().sum()
)

Missing values after numeric cleaning:
total_participants    0
age_18_29             0
age_30_39             0
age_40_49             0
age_50_59             0
age_60_69             0
age_70_79             0
age_80_89             0
age_90_99             0
age_100_plus          0
dtype: int64

In [ ]:
age_group_columns = [
    "age_18_29",
    "age_30_39",
    "age_40_49",
    "age_50_59",
    "age_60_69",
    "age_70_79",
    "age_80_89",
    "age_90_99",
    "age_100_plus",
]

age_2024["calculated_age_total"] = (
    age_2024[age_group_columns].sum(
        axis=1,
        min_count=len(age_group_columns)
    )
)

age_2024["age_total_difference"] = (
    age_2024["calculated_age_total"]
    - age_2024["total_participants"]
)

age_2024_discrepancies = age_2024.loc[
    age_2024["age_total_difference"] != 0,
    [
        "county_name",
        "total_participants",
        "calculated_age_total",
        "age_total_difference",
    ]
]

print(
    "Counties with age-total discrepancies:",
    len(age_2024_discrepancies)
)

age_2024_discrepancies

Counties with age-total discrepancies: 0

Empty DataFrame
Columns: [county_name, total_participants, calculated_age_total, age_total_difference]
Index: []

In [ ]:
age_2024 = age_2024.drop(
    columns=[
        "calculated_age_total",
        "age_total_difference",
    ]
)



---

In [ ]:
age_2024_output = (
    CLEAN_2024
    / "age_participation_2024_clean.csv"
)

age_2024.to_csv(
    age_2024_output,
    index=False,
    encoding="utf-8"
)

print("Saved corrected file to:")
print(age_2024_output)

Saved corrected file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2024/age_participation_2024_clean.csv



---

# **DEMOGRAPHIC DATA: 2020 & 2024 GENDER**



---

# 2020 GENDER

In [ ]:
gender_2020_raw = pd.read_csv(
    RAW_2020 / "2020_Gender.csv"
)

print("Raw shape:", gender_2020_raw.shape)
print(gender_2020_raw.columns.tolist())

gender_2020_raw.head()

Raw shape: (68, 5)
['County', 'Total Ballots Cast', 'Total Female', 'Total Male', 'Total Not Identified']

    County Total Ballots Cast Total Female Total Male Total Not Identified
0  AUTAUGA             27,681       15,245     12,310                  126
1  BALDWIN            110,922       60,724     50,049                  149
2  BARBOUR             10,551        6,059      4,483                    9
3     BIBB              8,797        4,801      3,989                    7
4   BLOUNT             27,694       14,749     12,935                   10



---

In [ ]:
gender_2020 = gender_2020_raw.copy()

gender_2020 = gender_2020.rename(
    columns={
        "County": "county_name",
        "Total Ballots Cast": "total_participants",
        "Total Female": "female_votes",
        "Total Male": "male_votes",
        "Total Not Identified": "gender_not_identified",
    }
)

gender_2020["county_name"] = (
    gender_2020["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)
    .str.lower()
    .str.title()
)

gender_2020["county_name"] = gender_2020["county_name"].replace(
    {
        "Dekalb": "DeKalb",
        "St Clair": "St. Clair",
    }
)

gender_2020 = gender_2020[
    gender_2020["county_name"].str.upper() != "TOTALS"
].copy()

gender_2020.insert(0, "year", 2020)

gender_numeric_columns = [
    "total_participants",
    "female_votes",
    "male_votes",
    "gender_not_identified",
]

for column in gender_numeric_columns:
    gender_2020[column] = clean_numeric_column(
        gender_2020[column]
    )

gender_2020 = gender_2020[
    gender_2020["county_name"].isin(PROJECT_COUNTIES)
].copy()

gender_2020 = gender_2020.sort_values(
    "county_name"
).reset_index(drop=True)

print("Cleaned shape:", gender_2020.shape)

gender_2020.head()

Cleaned shape: (43, 6)

,year,county_name,total_participants,female_votes,male_votes,gender_not_identified
0,2020,Autauga,27681,15245,12310,126
1,2020,Bibb,8797,4801,3989,7
2,2020,Blount,27694,14749,12935,10
3,2020,Calhoun,51304,28296,22881,127
4,2020,Chambers,15481,8722,6725,34



---

In [ ]:
gender_counties_found = set(
    gender_2020["county_name"]
)

gender_missing_counties = sorted(
    set(PROJECT_COUNTIES) - gender_counties_found
)

gender_unexpected_counties = sorted(
    gender_counties_found - set(PROJECT_COUNTIES)
)

print("Missing counties:", gender_missing_counties)
print("Unexpected counties:", gender_unexpected_counties)

Missing counties: []
Unexpected counties: []

In [ ]:
gender_duplicates = gender_2020[
    gender_2020.duplicated(
        subset=["year", "county_name"],
        keep=False
    )
]

print(
    "Number of duplicate rows:",
    len(gender_duplicates)
)

gender_duplicates

Number of duplicate rows: 0

Empty DataFrame
Columns: [year, county_name, total_participants, female_votes, male_votes, gender_not_identified]
Index: []

In [ ]:
print(
    gender_2020.isna().sum()
)

year                     0
county_name              0
total_participants       0
female_votes             0
male_votes               0
gender_not_identified    0
dtype: int64

In [ ]:
gender_2020["calculated_gender_total"] = (
    gender_2020[
        [
            "female_votes",
            "male_votes",
            "gender_not_identified",
        ]
    ].sum(axis=1)
)

gender_2020["gender_total_difference"] = (
    gender_2020["calculated_gender_total"]
    - gender_2020["total_participants"]
)

gender_discrepancies = gender_2020.loc[
    gender_2020["gender_total_difference"] != 0,
    [
        "county_name",
        "total_participants",
        "calculated_gender_total",
        "gender_total_difference",
    ]
]

print(
    "Counties with gender-total discrepancies:",
    len(gender_discrepancies)
)

gender_discrepancies

Counties with gender-total discrepancies: 0

Empty DataFrame
Columns: [county_name, total_participants, calculated_gender_total, gender_total_difference]
Index: []

In [ ]:
gender_2020 = gender_2020.drop(
    columns=[
        "calculated_gender_total",
        "gender_total_difference",
    ]
)

gender_2020.head()

,year,county_name,total_participants,female_votes,male_votes,gender_not_identified
0,2020,Autauga,27681,15245,12310,126
1,2020,Bibb,8797,4801,3989,7
2,2020,Blount,27694,14749,12935,10
3,2020,Calhoun,51304,28296,22881,127
4,2020,Chambers,15481,8722,6725,34



---

In [ ]:
gender_2020_output = (
    CLEAN_2020
    / "gender_participation_2020_clean.csv"
)

gender_2020.to_csv(
    gender_2020_output,
    index=False,
    encoding="utf-8"
)

print("Saved cleaned gender file to:")
print(gender_2020_output)

Saved cleaned gender file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2020/gender_participation_2020_clean.csv

In [ ]:
gender_2020_check = pd.read_csv(
    gender_2020_output
)

print(
    "Saved file shape:",
    gender_2020_check.shape
)

print(gender_2020_check.dtypes)

gender_2020_check.head()

Saved file shape: (43, 6)
year                      int64
county_name              object
total_participants        int64
female_votes              int64
male_votes                int64
gender_not_identified     int64
dtype: object

,year,county_name,total_participants,female_votes,male_votes,gender_not_identified
0,2020,Autauga,27681,15245,12310,126
1,2020,Bibb,8797,4801,3989,7
2,2020,Blount,27694,14749,12935,10
3,2020,Calhoun,51304,28296,22881,127
4,2020,Chambers,15481,8722,6725,34



---

# 2024 GENDER

In [ ]:
gender_2024_raw = pd.read_csv(
    RAW_2024 / "2024_Gender.csv"
)

print("Raw shape:", gender_2024_raw.shape)
print(gender_2024_raw.columns.tolist())

gender_2024_raw.head()

Raw shape: (69, 5)
['County', 'Total Ballots Cast', 'Total Female', 'Total Male', 'Total Not Identified']

,County,Total Ballots Cast,Total Female,Total Male,Total Not Identified
0,2024 General Election Participation by Gender,NaN,NaN,NaN,NaN
1,AUTAUGA,"28,401","15,750","12,581",82
2,BALDWIN,"122,501","66,932","55,452",117
3,BARBOUR,"9,901","5,646","4,236",19
4,BIBB,"9,283","5,017","4,264",2



---

In [ ]:
gender_2024 = gender_2024_raw.copy()

gender_2024 = gender_2024.rename(
    columns={
        "County": "county_name",
        "Total Ballots Cast": "total_participants",
        "Total Female": "female_votes",
        "Total Male": "male_votes",
        "Total Not Identified": "gender_not_identified",
    }
)

gender_2024["county_name"] = (
    gender_2024["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)
    .str.lower()
    .str.title()
)

gender_2024["county_name"] = gender_2024["county_name"].replace(
    {
        "Dekalb": "DeKalb",
        "St Clair": "St. Clair",
    }
)

gender_2024 = gender_2024[
    ~gender_2024["county_name"].str.contains(
        "Election Participation",
        case=False,
        na=False
    )
].copy()

gender_2024 = gender_2024[
    gender_2024["county_name"].str.upper() != "TOTALS"
].copy()

gender_2024.insert(0, "year", 2024)

gender_numeric_columns = [
    "total_participants",
    "female_votes",
    "male_votes",
    "gender_not_identified",
]

for column in gender_numeric_columns:
    gender_2024[column] = clean_numeric_column(
        gender_2024[column]
    )

gender_2024 = gender_2024[
    gender_2024["county_name"].isin(PROJECT_COUNTIES)
].copy()

gender_2024 = gender_2024.sort_values(
    "county_name"
).reset_index(drop=True)

print("Cleaned shape:", gender_2024.shape)

gender_2024.head()

Cleaned shape: (43, 6)

,year,county_name,total_participants,female_votes,male_votes,gender_not_identified
0,2024,Autauga,28401,15750,12581,82
1,2024,Bibb,9283,5017,4264,2
2,2024,Blount,28255,15026,13213,16
3,2024,Calhoun,48732,27074,21581,77
4,2024,Chambers,13687,7725,5936,26



---

In [ ]:
gender_2024_counties_found = set(
    gender_2024["county_name"]
)

gender_2024_missing_counties = sorted(
    set(PROJECT_COUNTIES)
    - gender_2024_counties_found
)

gender_2024_unexpected_counties = sorted(
    gender_2024_counties_found
    - set(PROJECT_COUNTIES)
)

print(
    "Missing counties:",
    gender_2024_missing_counties
)

print(
    "Unexpected counties:",
    gender_2024_unexpected_counties
)

Missing counties: []
Unexpected counties: []

In [ ]:
gender_2024_duplicates = gender_2024[
    gender_2024.duplicated(
        subset=["year", "county_name"],
        keep=False
    )
]

print(
    "Number of duplicate rows:",
    len(gender_2024_duplicates)
)

gender_2024_duplicates

Number of duplicate rows: 0

Empty DataFrame
Columns: [year, county_name, total_participants, female_votes, male_votes, gender_not_identified]
Index: []

In [ ]:
print(
    gender_2024.isna().sum()
)

year                     0
county_name              0
total_participants       0
female_votes             0
male_votes               0
gender_not_identified    0
dtype: int64

In [ ]:
gender_2024["calculated_gender_total"] = (
    gender_2024[
        [
            "female_votes",
            "male_votes",
            "gender_not_identified",
        ]
    ].sum(
        axis=1,
        min_count=3
    )
)

gender_2024["gender_total_difference"] = (
    gender_2024["calculated_gender_total"]
    - gender_2024["total_participants"]
)

gender_2024_discrepancies = gender_2024.loc[
    gender_2024["gender_total_difference"] != 0,
    [
        "county_name",
        "total_participants",
        "female_votes",
        "male_votes",
        "gender_not_identified",
        "calculated_gender_total",
        "gender_total_difference",
    ]
]

print(
    "Counties with gender-total discrepancies:",
    len(gender_2024_discrepancies)
)

gender_2024_discrepancies

Counties with gender-total discrepancies: 1

,county_name,total_participants,female_votes,male_votes,gender_not_identified,calculated_gender_total,gender_total_difference
0,Autauga,28401,15750,12581,82,28413,12

*2024 Gender Autauga County: Gender categories exceed Total Ballots Cast by 12*

In [ ]:
gender_2024 = gender_2024.drop(
    columns=[
        "calculated_gender_total",
        "gender_total_difference",
    ]
)

gender_2024.head()

,year,county_name,total_participants,female_votes,male_votes,gender_not_identified
0,2024,Autauga,28401,15750,12581,82
1,2024,Bibb,9283,5017,4264,2
2,2024,Blount,28255,15026,13213,16
3,2024,Calhoun,48732,27074,21581,77
4,2024,Chambers,13687,7725,5936,26

In [ ]:
gender_2024_output = (
    CLEAN_2024
    / "gender_participation_2024_clean.csv"
)

gender_2024.to_csv(
    gender_2024_output,
    index=False,
    encoding="utf-8"
)

print("Saved cleaned gender file to:")
print(gender_2024_output)

Saved cleaned gender file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2024/gender_participation_2024_clean.csv

In [ ]:
gender_2024_check = pd.read_csv(
    gender_2024_output
)

print(
    "Saved file shape:",
    gender_2024_check.shape
)

print(gender_2024_check.dtypes)

gender_2024_check.head()

Saved file shape: (43, 6)
year                      int64
county_name              object
total_participants        int64
female_votes              int64
male_votes                int64
gender_not_identified     int64
dtype: object

,year,county_name,total_participants,female_votes,male_votes,gender_not_identified
0,2024,Autauga,28401,15750,12581,82
1,2024,Bibb,9283,5017,4264,2
2,2024,Blount,28255,15026,13213,16
3,2024,Calhoun,48732,27074,21581,77
4,2024,Chambers,13687,7725,5936,26



---

# **DEMOGRAPHIC DATA: 2020 & 2024 RACE**



---

# 2020 RACE

In [ ]:
race_2020_raw = pd.read_csv(
    RAW_2020 / "2020_Race.csv"
)

print("Raw shape:", race_2020_raw.shape)
print(race_2020_raw.columns.tolist())

race_2020_raw.head()

Raw shape: (68, 11)
['County', 'Total Ballots Cast', 'Total Asian', 'Total American Indian', 'Total Black', 'Total Federally-Registered', 'Total Hispanic', 'Total Korean', 'Total Other', 'Total Not Identified', 'Total White']

,County,Total Ballots Cast,Total Asian,Total American Indian,Total Black,Total Federally-Registered,Total Hispanic,Total Korean,Total Other,Total Not Identified,Total White
0,AUTAUGA,"27,681",158,54,"5,091",0,189,0,184,120,"21,885"
1,BALDWIN,"110,922",524,445,"6,670",1,"1,065",0,727,344,"101,146"
2,BARBOUR,"10,551",17,14,"4,330",0,35,0,21,24,"6,110"
3,BIBB,"8,797",6,18,"1,422",0,25,0,12,14,"7,300"
4,BLOUNT,"27,694",53,61,299,1,475,1,116,43,"26,645"



---

In [ ]:
race_2020 = race_2020_raw.copy()

race_2020 = race_2020.rename(
    columns={
        "County": "county_name",
        "Total Ballots Cast": "total_participants",
        "Total Asian": "total_asian",
        "Total American Indian": "total_american_indian",
        "Total Black": "total_black",
        "Total Federally-Registered": "total_federally_registered",
        "Total Hispanic": "total_hispanic",
        "Total Korean": "total_korean",
        "Total Other": "total_other",
        "Total Not Identified": "total_not_identified",
        "Total White": "total_white",
    }
)

race_2020["county_name"] = (
    race_2020["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)
    .str.lower()
    .str.title()
)

race_2020["county_name"] = race_2020["county_name"].replace(
    {
        "Dekalb": "DeKalb",
        "St Clair": "St. Clair",
    }
)

race_2020 = race_2020[
    race_2020["county_name"].str.upper() != "TOTALS"
].copy()

race_2020.insert(0, "year", 2020)

race_numeric_columns = [
    "total_participants",
    "total_asian",
    "total_american_indian",
    "total_black",
    "total_federally_registered",
    "total_hispanic",
    "total_korean",
    "total_other",
    "total_not_identified",
    "total_white",
]

for column in race_numeric_columns:
    race_2020[column] = clean_numeric_column(
        race_2020[column]
    )

race_2020 = race_2020[
    race_2020["county_name"].isin(PROJECT_COUNTIES)
].copy()

race_2020 = race_2020.sort_values(
    "county_name"
).reset_index(drop=True)

print("Cleaned shape:", race_2020.shape)

race_2020.head()

Cleaned shape: (43, 12)

,year,county_name,total_participants,total_asian,total_american_indian,total_black,total_federally_registered,total_hispanic,total_korean,total_other,total_not_identified,total_white
0,2020,Autauga,27681,158,54,5091,0,189,0,184,120,21885
1,2020,Bibb,8797,6,18,1422,0,25,0,12,14,7300
2,2020,Blount,27694,53,61,299,1,475,1,116,43,26645
3,2020,Calhoun,51304,232,119,9540,1,430,0,339,253,40390
4,2020,Chambers,15481,47,20,5636,0,42,0,64,60,9612



---

In [ ]:
race_counties_found = set(
    race_2020["county_name"]
)

race_missing_counties = sorted(
    set(PROJECT_COUNTIES) - race_counties_found
)

race_unexpected_counties = sorted(
    race_counties_found - set(PROJECT_COUNTIES)
)

print("Missing counties:", race_missing_counties)
print("Unexpected counties:", race_unexpected_counties)

Missing counties: []
Unexpected counties: []

In [ ]:
race_duplicates = race_2020[
    race_2020.duplicated(
        subset=["year", "county_name"],
        keep=False
    )
]

print(
    "Number of duplicate rows:",
    len(race_duplicates)
)

race_duplicates

Number of duplicate rows: 0

Empty DataFrame
Columns: [year, county_name, total_participants, total_asian, total_american_indian, total_black, total_federally_registered, total_hispanic, total_korean, total_other, total_not_identified, total_white]
Index: []

In [ ]:
print(
    race_2020.isna().sum()
)

year                          0
county_name                   0
total_participants            0
total_asian                   0
total_american_indian         0
total_black                   0
total_federally_registered    0
total_hispanic                0
total_korean                  0
total_other                   0
total_not_identified          0
total_white                   0
dtype: int64

In [ ]:
race_category_columns = [
    "total_asian",
    "total_american_indian",
    "total_black",
    "total_federally_registered",
    "total_hispanic",
    "total_korean",
    "total_other",
    "total_not_identified",
    "total_white",
]

race_2020["calculated_race_total"] = (
    race_2020[race_category_columns].sum(axis=1)
)

race_2020["race_total_difference"] = (
    race_2020["calculated_race_total"]
    - race_2020["total_participants"]
)

race_discrepancies = race_2020.loc[
    race_2020["race_total_difference"] != 0,
    [
        "county_name",
        "total_participants",
        "calculated_race_total",
        "race_total_difference",
    ]
]

print(
    "Counties with race-total discrepancies:",
    len(race_discrepancies)
)

race_discrepancies

Counties with race-total discrepancies: 0

Empty DataFrame
Columns: [county_name, total_participants, calculated_race_total, race_total_difference]
Index: []

In [ ]:
race_2020[
    [
        "county_name",
        "total_federally_registered",
        "total_korean",
    ]
].sort_values(
    [
        "total_federally_registered",
        "total_korean",
    ],
    ascending=False
).head(15)

   county_name  total_federally_registered  total_korean
24   Jefferson                         933             2
6      Chilton                           3             0
19    Franklin                           3             0
28         Lee                           2             4
40  Tuscaloosa                           1             2
2       Blount                           1             1
3      Calhoun                           1             0
13     Cullman                           1             0
22     Houston                           1             0
30     Madison                           1             0
32    Marshall                           1             0
33      Morgan                           1             0
38   Talladega                           1             0
29   Limestone                           0             3
9       Coffee                           0             1

In [ ]:
race_2020 = race_2020.drop(
    columns=[
        "calculated_race_total",
        "race_total_difference",
    ]
)

race_2020.head()

,year,county_name,total_participants,total_asian,total_american_indian,total_black,total_federally_registered,total_hispanic,total_korean,total_other,total_not_identified,total_white
0,2020,Autauga,27681,158,54,5091,0,189,0,184,120,21885
1,2020,Bibb,8797,6,18,1422,0,25,0,12,14,7300
2,2020,Blount,27694,53,61,299,1,475,1,116,43,26645
3,2020,Calhoun,51304,232,119,9540,1,430,0,339,253,40390
4,2020,Chambers,15481,47,20,5636,0,42,0,64,60,9612



---

In [ ]:
race_2020_output = (
    CLEAN_2020
    / "race_participation_2020_clean.csv"
)

race_2020.to_csv(
    race_2020_output,
    index=False,
    encoding="utf-8"
)

print("Saved cleaned race file to:")
print(race_2020_output)

Saved cleaned race file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2020/race_participation_2020_clean.csv

In [ ]:
race_2020_check = pd.read_csv(
    race_2020_output
)

print(
    "Saved file shape:",
    race_2020_check.shape
)

print(race_2020_check.dtypes)

race_2020_check.head()

Saved file shape: (43, 12)
year                           int64
county_name                   object
total_participants             int64
total_asian                    int64
total_american_indian          int64
total_black                    int64
total_federally_registered     int64
total_hispanic                 int64
total_korean                   int64
total_other                    int64
total_not_identified           int64
total_white                    int64
dtype: object

,year,county_name,total_participants,total_asian,total_american_indian,total_black,total_federally_registered,total_hispanic,total_korean,total_other,total_not_identified,total_white
0,2020,Autauga,27681,158,54,5091,0,189,0,184,120,21885
1,2020,Bibb,8797,6,18,1422,0,25,0,12,14,7300
2,2020,Blount,27694,53,61,299,1,475,1,116,43,26645
3,2020,Calhoun,51304,232,119,9540,1,430,0,339,253,40390
4,2020,Chambers,15481,47,20,5636,0,42,0,64,60,9612



---

# 2024 RACE

In [ ]:
race_2024_raw = pd.read_csv(
    RAW_2024 / "2024_Race.csv"
)

print("Raw shape:", race_2024_raw.shape)
print(race_2024_raw.columns.tolist())

race_2024_raw.head()

Raw shape: (69, 11)
['County', 'Total Ballots Cast', 'Total Asian', 'Total American Indian', 'Total Black', 'Total Federally-Registered', 'Total Hispanic', 'Total Korean', 'Total Other', 'Total White', 'Total Not Identified']

,County,Total Ballots Cast,Total Asian,Total American Indian,Total Black,Total Federally-Registered,Total Hispanic,Total Korean,Total Other,Total White,Total Not Identified
0,2024 General Election Participation by Race,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AUTAUGA,"28,401",164,46,"5,114",0.0,225,0.0,205,"22,571",76
2,BALDWIN,"122,501",667,390,"6,117",0.0,"1,361",0.0,740,"112,966",260
3,BARBOUR,"9,901",21,11,"3,773",0.0,50,0.0,27,"5,979",40
4,BIBB,"9,283",6,12,"1,239",0.0,35,0.0,19,"7,947",25



---

In [ ]:
race_2024 = race_2024_raw.copy()

race_2024 = race_2024.rename(
    columns={
        "County": "county_name",
        "Total Ballots Cast": "total_participants",
        "Total Asian": "total_asian",
        "Total American Indian": "total_american_indian",
        "Total Black": "total_black",
        "Total Federally-Registered": "total_federally_registered",
        "Total Hispanic": "total_hispanic",
        "Total Korean": "total_korean",
        "Total Other": "total_other",
        "Total White": "total_white",
        "Total Not Identified": "total_not_identified",
    }
)

race_2024["county_name"] = (
    race_2024["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)
    .str.lower()
    .str.title()
)

race_2024["county_name"] = race_2024["county_name"].replace(
    {
        "Dekalb": "DeKalb",
        "St Clair": "St. Clair",
    }
)

race_2024 = race_2024[
    ~race_2024["county_name"].str.contains(
        "Election Participation",
        case=False,
        na=False
    )
].copy()

race_2024 = race_2024[
    race_2024["county_name"].str.upper() != "TOTALS"
].copy()

race_2024.insert(0, "year", 2024)

race_numeric_columns = [
    "total_participants",
    "total_asian",
    "total_american_indian",
    "total_black",
    "total_federally_registered",
    "total_hispanic",
    "total_korean",
    "total_other",
    "total_white",
    "total_not_identified",
]

for column in race_numeric_columns:
    race_2024[column] = clean_numeric_column(
        race_2024[column]
    )

race_2024 = race_2024[
    race_2024["county_name"].isin(PROJECT_COUNTIES)
].copy()

race_2024 = race_2024.sort_values(
    "county_name"
).reset_index(drop=True)

print("Cleaned shape:", race_2024.shape)

race_2024.head()

Cleaned shape: (43, 12)

,year,county_name,total_participants,total_asian,total_american_indian,total_black,total_federally_registered,total_hispanic,total_korean,total_other,total_white,total_not_identified
0,2024,Autauga,28401,164,46,5114,0,225,0,205,22571,76
1,2024,Bibb,9283,6,12,1239,0,35,0,19,7947,25
2,2024,Blount,28255,70,48,321,1,572,0,128,27068,47
3,2024,Calhoun,48732,192,79,8243,0,478,0,376,39190,174
4,2024,Chambers,13687,38,17,4468,0,51,0,54,9017,42



---

In [ ]:
race_2024_counties_found = set(
    race_2024["county_name"]
)

race_2024_missing_counties = sorted(
    set(PROJECT_COUNTIES)
    - race_2024_counties_found
)

race_2024_unexpected_counties = sorted(
    race_2024_counties_found
    - set(PROJECT_COUNTIES)
)

print(
    "Missing counties:",
    race_2024_missing_counties
)

print(
    "Unexpected counties:",
    race_2024_unexpected_counties
)

Missing counties: []
Unexpected counties: []

In [ ]:
race_2024_duplicates = race_2024[
    race_2024.duplicated(
        subset=["year", "county_name"],
        keep=False
    )
]

print(
    "Number of duplicate rows:",
    len(race_2024_duplicates)
)

race_2024_duplicates

Number of duplicate rows: 0

Empty DataFrame
Columns: [year, county_name, total_participants, total_asian, total_american_indian, total_black, total_federally_registered, total_hispanic, total_korean, total_other, total_white, total_not_identified]
Index: []

In [ ]:
race_2024_missing_values = (
    race_2024.isna().sum()
)

print(race_2024_missing_values)

year                          0
county_name                   0
total_participants            0
total_asian                   0
total_american_indian         0
total_black                   0
total_federally_registered    1
total_hispanic                0
total_korean                  0
total_other                   0
total_white                   0
total_not_identified          0
dtype: int64

In [ ]:
race_2024[
    race_2024["total_federally_registered"].isna()
]

,year,county_name,total_participants,total_asian,total_american_indian,total_black,total_federally_registered,total_hispanic,total_korean,total_other,total_white,total_not_identified
35,2024,Randolph,11145,24,14,1382,<NA>,42,0,42,9616,25

In [ ]:
randolph_race_check = race_2024.loc[
    race_2024["county_name"] == "Randolph",
    [
        "county_name",
        "total_participants",
        "total_asian",
        "total_american_indian",
        "total_black",
        "total_federally_registered",
        "total_hispanic",
        "total_korean",
        "total_other",
        "total_white",
        "total_not_identified",
    ]
]

randolph_race_check

,county_name,total_participants,total_asian,total_american_indian,total_black,total_federally_registered,total_hispanic,total_korean,total_other,total_white,total_not_identified
35,Randolph,11145,24,14,1382,<NA>,42,0,42,9616,25

*Randolph County: total Federally-Registered is blank kept as missing rather than assuming zero*

In [ ]:
race_category_columns = [
    "total_asian",
    "total_american_indian",
    "total_black",
    "total_federally_registered",
    "total_hispanic",
    "total_korean",
    "total_other",
    "total_white",
    "total_not_identified",
]

race_2024["calculated_race_total"] = (
    race_2024[race_category_columns].sum(
        axis=1,
        min_count=len(race_category_columns)
    )
)

race_2024["race_total_difference"] = (
    race_2024["calculated_race_total"]
    - race_2024["total_participants"]
)

In [ ]:
race_2024_incomplete_rows = race_2024[
    race_2024["calculated_race_total"].isna()
]

print(
    "Rows that could not be fully validated because of missing values:",
    len(race_2024_incomplete_rows)
)

race_2024_incomplete_rows[
    [
        "county_name",
        "total_participants",
        "total_federally_registered",
        "calculated_race_total",
    ]
]

Rows that could not be fully validated because of missing values: 1

,county_name,total_participants,total_federally_registered,calculated_race_total
35,Randolph,11145,<NA>,<NA>

In [ ]:
race_2024["race_total_excluding_missing"] = (
    race_2024[race_category_columns].sum(
        axis=1,
        skipna=True
    )
)

race_2024.loc[
    race_2024["county_name"] == "Randolph",
    [
        "county_name",
        "total_participants",
        "total_federally_registered",
        "race_total_excluding_missing",
    ]
]

,county_name,total_participants,total_federally_registered,race_total_excluding_missing
35,Randolph,11145,<NA>,11145

In [ ]:
race_2024 = race_2024.drop(
    columns=[
        "calculated_race_total",
        "race_total_difference",
        "race_total_excluding_missing",
    ]
)

race_2024.head()

,year,county_name,total_participants,total_asian,total_american_indian,total_black,total_federally_registered,total_hispanic,total_korean,total_other,total_white,total_not_identified
0,2024,Autauga,28401,164,46,5114,0,225,0,205,22571,76
1,2024,Bibb,9283,6,12,1239,0,35,0,19,7947,25
2,2024,Blount,28255,70,48,321,1,572,0,128,27068,47
3,2024,Calhoun,48732,192,79,8243,0,478,0,376,39190,174
4,2024,Chambers,13687,38,17,4468,0,51,0,54,9017,42



---

In [ ]:
race_2024_output = (
    CLEAN_2024
    / "race_participation_2024_clean.csv"
)

race_2024.to_csv(
    race_2024_output,
    index=False,
    encoding="utf-8"
)

print("Saved cleaned race file to:")
print(race_2024_output)

Saved cleaned race file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2024/race_participation_2024_clean.csv

In [ ]:
race_2024_check = pd.read_csv(
    race_2024_output
)

print(
    "Saved file shape:",
    race_2024_check.shape
)

print(race_2024_check.dtypes)

race_2024_check.head()

Saved file shape: (43, 12)
year                            int64
county_name                    object
total_participants              int64
total_asian                     int64
total_american_indian           int64
total_black                     int64
total_federally_registered    float64
total_hispanic                  int64
total_korean                    int64
total_other                     int64
total_white                     int64
total_not_identified            int64
dtype: object

,year,county_name,total_participants,total_asian,total_american_indian,total_black,total_federally_registered,total_hispanic,total_korean,total_other,total_white,total_not_identified
0,2024,Autauga,28401,164,46,5114,0.0,225,0,205,22571,76
1,2024,Bibb,9283,6,12,1239,0.0,35,0,19,7947,25
2,2024,Blount,28255,70,48,321,1.0,572,0,128,27068,47
3,2024,Calhoun,48732,192,79,8243,0.0,478,0,376,39190,174
4,2024,Chambers,13687,38,17,4468,0.0,51,0,54,9017,42



---

**COMBINING DEMOGRAPHIC FILES**

In [ ]:
age_participation_combined = pd.concat(
    [age_2020, age_2024],
    ignore_index=True
)

age_participation_combined = (
    age_participation_combined
    .sort_values(["county_name", "year"])
    .reset_index(drop=True)
)

print("Combined shape:", age_participation_combined.shape)

print(
    age_participation_combined
    .groupby("year")["county_name"]
    .nunique()
)

age_participation_combined.to_csv(
    CLEAN_COMBINED / "age_participation_clean.csv",
    index=False,
    encoding="utf-8"
)

print("Saved combined age participation file.")

Combined shape: (86, 12)
year
2020    43
2024    43
Name: county_name, dtype: int64
Saved combined age participation file.

In [ ]:
gender_participation_combined = pd.concat(
    [gender_2020, gender_2024],
    ignore_index=True
)

gender_participation_combined = (
    gender_participation_combined
    .sort_values(["county_name", "year"])
    .reset_index(drop=True)
)

print("Combined shape:", gender_participation_combined.shape)

print(
    gender_participation_combined
    .groupby("year")["county_name"]
    .nunique()
)

gender_participation_combined.to_csv(
    CLEAN_COMBINED / "gender_participation_clean.csv",
    index=False,
    encoding="utf-8"
)

Combined shape: (86, 6)
year
2020    43
2024    43
Name: county_name, dtype: int64

In [ ]:
race_participation_combined = pd.concat(
    [race_2020, race_2024],
    ignore_index=True
)

race_participation_combined = (
    race_participation_combined
    .sort_values(["county_name", "year"])
    .reset_index(drop=True)
)

print("Combined shape:", race_participation_combined.shape)

print(
    race_participation_combined
    .groupby("year")["county_name"]
    .nunique()
)

race_participation_combined.to_csv(
    CLEAN_COMBINED / "race_participation_clean.csv",
    index=False,
    encoding="utf-8"
)

Combined shape: (86, 12)
year
2020    43
2024    43
Name: county_name, dtype: int64

# **VOTER REGISTRATION**



---

In [ ]:
registration_2020_file = pd.ExcelFile(
    RAW_2020 / "ALVR-2020.xls"
)

registration_2024_file = pd.ExcelFile(
    RAW_2024 / "ALVR-2024.xlsx"
)

print("2020 sheets:")
print(registration_2020_file.sheet_names)

print("\n2024 sheets:")
print(registration_2024_file.sheet_names)

2020 sheets:
['January', '2020 Primary Election', 'February', 'March', 'April', 'May', 'June', '2020 Primary Runoff', 'July', 'August', 'September', '2020 General', 'October', 'November', 'December']

2024 sheets:
['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

**Defining cleaned columns**

In [ ]:
registration_columns = [
    "county_name",
    "registered_total",

    "active_asian",
    "active_american_indian",
    "active_black",
    "active_federally_registered",
    "active_hispanic",
    "active_korean",
    "active_white",
    "active_other",
    "active_not_identified",
    "active_total",

    "inactive_asian",
    "inactive_american_indian",
    "inactive_black",
    "inactive_federally_registered",
    "inactive_hispanic",
    "inactive_korean",
    "inactive_white",
    "inactive_other",
    "inactive_not_identified",
    "inactive_total",
]



---

# 2020 ALVR

In [ ]:
registration_2020_raw = pd.read_excel(
    RAW_2020 / "ALVR-2020.xls",
    sheet_name="2020 General",
    header=None,
    skiprows=2,
    names=registration_columns,
)

print("Raw shape:", registration_2020_raw.shape)

registration_2020_raw.head()

Raw shape: (68, 22)

,county_name,registered_total,active_asian,active_american_indian,active_black,active_federally_registered,active_hispanic,active_korean,active_white,active_other,...,inactive_asian,inactive_american_indian,inactive_black,inactive_federally_registered,inactive_hispanic,inactive_korean,inactive_white,inactive_other,inactive_not_identified,inactive_total
0,TOTAL,3708804,25323,10552,920214,1416.0,40949,29.0,2444135,25176,...,1862.0,963.0,65759,133.0,3232.0,4.0,142410,4096.0,1086.0,219545
1,AUTAUGA,43482,269,89,7992,NaN,329,NaN,31619,298,...,27.0,20.0,501,NaN,35.0,NaN,1933,55.0,30.0,2601
2,BALDWIN,176642,878,704,12172,1.0,2120,NaN,148056,1216,...,55.0,70.0,915,NaN,190.0,NaN,9371,163.0,30.0,10794
3,BARBOUR,17819,45,25,7903,1.0,98,NaN,8590,51,...,5.0,3.0,431,NaN,9.0,NaN,567,4.0,2.0,1021
4,BIBB,14992,11,29,2575,NaN,55,NaN,11627,23,...,3.0,4.0,152,NaN,2.0,NaN,478,2.0,NaN,641



---

**Cleaning:**


*   removed empty rows
*   standardized county names


*   corrected the spelling of the special county names
*   removed statewide total row


*   added year to be the first column


*   cleaned numeric columns


*   Blank cells for 0 registered voters are changed to 0


*   kept only the 43 relevant counties

In [ ]:
registration_2020 = registration_2020_raw.copy()

registration_2020 = registration_2020[
    registration_2020["county_name"].notna()
].copy()

registration_2020["county_name"] = (
    registration_2020["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)
    .str.lower()
    .str.title()
)

registration_2020["county_name"] = (
    registration_2020["county_name"].replace(
        {
            "Dekalb": "DeKalb",
            "St Clair": "St. Clair",
        }
    )
)

registration_2020 = registration_2020[
    registration_2020["county_name"].str.upper() != "TOTAL"
].copy()

registration_2020.insert(0, "year", 2020)

In [ ]:
registration_numeric_columns = [
    column
    for column in registration_columns
    if column != "county_name"
]

for column in registration_numeric_columns:
    registration_2020[column] = clean_numeric_column(
        registration_2020[column]
    )

In [ ]:
registration_category_columns = [
    "active_asian",
    "active_american_indian",
    "active_black",
    "active_federally_registered",
    "active_hispanic",
    "active_korean",
    "active_white",
    "active_other",
    "active_not_identified",

    "inactive_asian",
    "inactive_american_indian",
    "inactive_black",
    "inactive_federally_registered",
    "inactive_hispanic",
    "inactive_korean",
    "inactive_white",
    "inactive_other",
    "inactive_not_identified",
]

registration_2020[
    registration_category_columns
] = registration_2020[
    registration_category_columns
].fillna(0)

In [ ]:
for column in registration_category_columns:
    registration_2020[column] = (
        registration_2020[column].astype("Int64")
    )

In [ ]:
registration_2020 = registration_2020[
    registration_2020["county_name"].isin(
        PROJECT_COUNTIES
    )
].copy()

registration_2020 = registration_2020.sort_values(
    "county_name"
).reset_index(drop=True)

print("Cleaned shape:", registration_2020.shape)

registration_2020.head()

Cleaned shape: (43, 23)

,year,county_name,registered_total,active_asian,active_american_indian,active_black,active_federally_registered,active_hispanic,active_korean,active_white,...,inactive_asian,inactive_american_indian,inactive_black,inactive_federally_registered,inactive_hispanic,inactive_korean,inactive_white,inactive_other,inactive_not_identified,inactive_total
0,2020,Autauga,43482,269,89,7992,0,329,0,31619,...,27,20,501,0,35,0,1933,55,30,2601
1,2020,Bibb,14992,11,29,2575,0,55,0,11627,...,3,4,152,0,2,0,478,2,0,641
2,2020,Blount,41865,75,106,603,2,1083,1,38233,...,6,7,29,0,33,0,1382,20,7,1484
3,2020,Calhoun,81390,421,184,15518,2,819,0,58307,...,33,24,1467,0,77,0,3228,92,45,4966
4,2020,Chambers,25985,92,34,9857,0,107,0,14355,...,13,3,536,0,5,0,701,10,9,1277



---

**Checking**

In [ ]:
registration_2020_counties_found = set(
    registration_2020["county_name"]
)

registration_2020_missing_counties = sorted(
    set(PROJECT_COUNTIES)
    - registration_2020_counties_found
)

registration_2020_unexpected_counties = sorted(
    registration_2020_counties_found
    - set(PROJECT_COUNTIES)
)

print(
    "Missing counties:",
    registration_2020_missing_counties
)

print(
    "Unexpected counties:",
    registration_2020_unexpected_counties
)

Missing counties: []
Unexpected counties: []

In [ ]:
registration_2020_duplicates = registration_2020[
    registration_2020.duplicated(
        subset=["year", "county_name"],
        keep=False,
    )
]

print(
    "Number of duplicate rows:",
    len(registration_2020_duplicates)
)

registration_2020_duplicates

Number of duplicate rows: 0

Empty DataFrame
Columns: [year, county_name, registered_total, active_asian, active_american_indian, active_black, active_federally_registered, active_hispanic, active_korean, active_white, active_other, active_not_identified, active_total, inactive_asian, inactive_american_indian, inactive_black, inactive_federally_registered, inactive_hispanic, inactive_korean, inactive_white, inactive_other, inactive_not_identified, inactive_total]
Index: []

[0 rows x 23 columns]

In [ ]:
print(
    registration_2020.isna().sum()
)

year                             0
county_name                      0
registered_total                 0
active_asian                     0
active_american_indian           0
active_black                     0
active_federally_registered      0
active_hispanic                  0
active_korean                    0
active_white                     0
active_other                     0
active_not_identified            0
active_total                     0
inactive_asian                   0
inactive_american_indian         0
inactive_black                   0
inactive_federally_registered    0
inactive_hispanic                0
inactive_korean                  0
inactive_white                   0
inactive_other                   0
inactive_not_identified          0
inactive_total                   0
dtype: int64

In [ ]:
active_registration_columns = [
    "active_asian",
    "active_american_indian",
    "active_black",
    "active_federally_registered",
    "active_hispanic",
    "active_korean",
    "active_white",
    "active_other",
    "active_not_identified",
]

registration_2020["calculated_active_total"] = (
    registration_2020[
        active_registration_columns
    ].sum(axis=1)
)

registration_2020["active_total_difference"] = (
    registration_2020["calculated_active_total"]
    - registration_2020["active_total"]
)

active_2020_discrepancies = registration_2020.loc[
    registration_2020["active_total_difference"] != 0,
    [
        "county_name",
        "active_total",
        "calculated_active_total",
        "active_total_difference",
    ],
]

print(
    "Counties with active-total discrepancies:",
    len(active_2020_discrepancies)
)

active_2020_discrepancies

Counties with active-total discrepancies: 0

Empty DataFrame
Columns: [county_name, active_total, calculated_active_total, active_total_difference]
Index: []

In [ ]:
inactive_registration_columns = [
    "inactive_asian",
    "inactive_american_indian",
    "inactive_black",
    "inactive_federally_registered",
    "inactive_hispanic",
    "inactive_korean",
    "inactive_white",
    "inactive_other",
    "inactive_not_identified",
]

registration_2020["calculated_inactive_total"] = (
    registration_2020[
        inactive_registration_columns
    ].sum(axis=1)
)

registration_2020["inactive_total_difference"] = (
    registration_2020["calculated_inactive_total"]
    - registration_2020["inactive_total"]
)

inactive_2020_discrepancies = registration_2020.loc[
    registration_2020["inactive_total_difference"] != 0,
    [
        "county_name",
        "inactive_total",
        "calculated_inactive_total",
        "inactive_total_difference",
    ],
]

print(
    "Counties with inactive-total discrepancies:",
    len(inactive_2020_discrepancies)
)

inactive_2020_discrepancies

Counties with inactive-total discrepancies: 0

Empty DataFrame
Columns: [county_name, inactive_total, calculated_inactive_total, inactive_total_difference]
Index: []

In [ ]:
registration_2020["calculated_registered_total"] = (
    registration_2020["active_total"]
    + registration_2020["inactive_total"]
)

registration_2020["registered_total_difference"] = (
    registration_2020["calculated_registered_total"]
    - registration_2020["registered_total"]
)

overall_2020_discrepancies = registration_2020.loc[
    registration_2020["registered_total_difference"] != 0,
    [
        "county_name",
        "registered_total",
        "active_total",
        "inactive_total",
        "calculated_registered_total",
        "registered_total_difference",
    ],
]

print(
    "Counties with overall registration discrepancies:",
    len(overall_2020_discrepancies)
)

overall_2020_discrepancies

Counties with overall registration discrepancies: 0

Empty DataFrame
Columns: [county_name, registered_total, active_total, inactive_total, calculated_registered_total, registered_total_difference]
Index: []

In [ ]:
registration_2020 = registration_2020.drop(
    columns=[
        "calculated_active_total",
        "active_total_difference",
        "calculated_inactive_total",
        "inactive_total_difference",
        "calculated_registered_total",
        "registered_total_difference",
    ]
)



---

In [ ]:
registration_2020_output = (
    CLEAN_2020
    / "voter_registration_2020_clean.csv"
)

registration_2020.to_csv(
    registration_2020_output,
    index=False,
    encoding="utf-8",
)

print("Saved cleaned 2020 registration file to:")
print(registration_2020_output)

Saved cleaned 2020 registration file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2020/voter_registration_2020_clean.csv

In [ ]:
registration_2020_check = pd.read_csv(
    registration_2020_output
)

print(
    "Saved file shape:",
    registration_2020_check.shape
)

registration_2020_check.head()

Saved file shape: (43, 23)

,year,county_name,registered_total,active_asian,active_american_indian,active_black,active_federally_registered,active_hispanic,active_korean,active_white,...,inactive_asian,inactive_american_indian,inactive_black,inactive_federally_registered,inactive_hispanic,inactive_korean,inactive_white,inactive_other,inactive_not_identified,inactive_total
0,2020,Autauga,43482,269,89,7992,0,329,0,31619,...,27,20,501,0,35,0,1933,55,30,2601
1,2020,Bibb,14992,11,29,2575,0,55,0,11627,...,3,4,152,0,2,0,478,2,0,641
2,2020,Blount,41865,75,106,603,2,1083,1,38233,...,6,7,29,0,33,0,1382,20,7,1484
3,2020,Calhoun,81390,421,184,15518,2,819,0,58307,...,33,24,1467,0,77,0,3228,92,45,4966
4,2020,Chambers,25985,92,34,9857,0,107,0,14355,...,13,3,536,0,5,0,701,10,9,1277



---

# 2024 ALVR

In [ ]:
registration_2024_raw = pd.read_excel(
    RAW_2024 / "ALVR-2024.xlsx",
    sheet_name="November",
    header=None,
    skiprows=2,
    names=registration_columns,
)

print("Raw shape:", registration_2024_raw.shape)

registration_2024_raw.head()

Raw shape: (68, 22)

,county_name,registered_total,active_asian,active_american_indian,active_black,active_federally_registered,active_hispanic,active_korean,active_white,active_other,...,inactive_asian,inactive_american_indian,inactive_black,inactive_federally_registered,inactive_hispanic,inactive_korean,inactive_white,inactive_other,inactive_not_identified,inactive_total
0,TOTAL,3880115,27591,8963,904149,742.0,52834,16.0,2449567,31641,...,4575.0,1378.0,116700,43.0,7887.0,6.0,246449,5564,4752,387354
1,AUTAUGA,46518,293,71,8588,NaN,443,NaN,32171,388,...,50.0,17.0,907,NaN,91.0,NaN,3182,62,71,4380
2,BALDWIN,208997,1192,602,12774,NaN,2825,NaN,164183,1334,...,187.0,123.0,2021,NaN,522.0,NaN,22262,255,145,25515
3,BARBOUR,17694,42,19,7224,NaN,148,NaN,8155,74,...,11.0,4.0,935,1.0,29.0,NaN,908,10,16,1914
4,BIBB,15161,14,19,2507,NaN,77,NaN,11676,38,...,5.0,2.0,191,NaN,8.0,NaN,576,2,3,787



---

In [ ]:
registration_2024 = registration_2024_raw.copy()

registration_2024 = registration_2024[
    registration_2024["county_name"].notna()
].copy()

registration_2024["county_name"] = (
    registration_2024["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)
    .str.lower()
    .str.title()
)

registration_2024["county_name"] = (
    registration_2024["county_name"].replace(
        {
            "Dekalb": "DeKalb",
            "St Clair": "St. Clair",
        }
    )
)

registration_2024 = registration_2024[
    registration_2024["county_name"].str.upper() != "TOTAL"
].copy()

registration_2024.insert(0, "year", 2024)

In [ ]:
for column in registration_numeric_columns:
    registration_2024[column] = clean_numeric_column(
        registration_2024[column]
    )

In [ ]:
registration_2024[
    registration_category_columns
] = registration_2024[
    registration_category_columns
].fillna(0)

for column in registration_category_columns:
    registration_2024[column] = (
        registration_2024[column].astype("Int64")
    )

In [ ]:
registration_2024 = registration_2024[
    registration_2024["county_name"].isin(
        PROJECT_COUNTIES
    )
].copy()

registration_2024 = registration_2024.sort_values(
    "county_name"
).reset_index(drop=True)

print("Cleaned shape:", registration_2024.shape)

registration_2024.head()

Cleaned shape: (43, 23)

,year,county_name,registered_total,active_asian,active_american_indian,active_black,active_federally_registered,active_hispanic,active_korean,active_white,...,inactive_asian,inactive_american_indian,inactive_black,inactive_federally_registered,inactive_hispanic,inactive_korean,inactive_white,inactive_other,inactive_not_identified,inactive_total
0,2024,Autauga,46518,293,71,8588,0,443,0,32171,...,50,17,907,0,91,0,3182,62,71,4380
1,2024,Bibb,15161,14,19,2507,0,77,0,11676,...,5,2,191,0,8,0,576,2,3,787
2,2024,Blount,43611,105,75,712,1,1491,0,38724,...,8,12,70,0,83,0,1994,24,11,2202
3,2024,Calhoun,84633,409,132,15508,0,1007,0,58834,...,75,30,2108,1,128,0,4903,122,114,7481
4,2024,Chambers,26877,89,33,9467,0,148,0,14118,...,30,3,1178,0,24,0,1480,21,24,2760



---

In [ ]:
registration_2024_counties_found = set(
    registration_2024["county_name"]
)

registration_2024_missing_counties = sorted(
    set(PROJECT_COUNTIES)
    - registration_2024_counties_found
)

registration_2024_unexpected_counties = sorted(
    registration_2024_counties_found
    - set(PROJECT_COUNTIES)
)

print(
    "Missing counties:",
    registration_2024_missing_counties
)

print(
    "Unexpected counties:",
    registration_2024_unexpected_counties
)

Missing counties: []
Unexpected counties: []

In [ ]:
registration_2024_duplicates = registration_2024[
    registration_2024.duplicated(
        subset=["year", "county_name"],
        keep=False,
    )
]

print(
    "Number of duplicate rows:",
    len(registration_2024_duplicates)
)

print("\nMissing values:")
print(registration_2024.isna().sum())

Number of duplicate rows: 0

Missing values:
year                             0
county_name                      0
registered_total                 0
active_asian                     0
active_american_indian           0
active_black                     0
active_federally_registered      0
active_hispanic                  0
active_korean                    0
active_white                     0
active_other                     0
active_not_identified            0
active_total                     0
inactive_asian                   0
inactive_american_indian         0
inactive_black                   0
inactive_federally_registered    0
inactive_hispanic                0
inactive_korean                  0
inactive_white                   0
inactive_other                   0
inactive_not_identified          0
inactive_total                   0
dtype: int64

In [ ]:
registration_2024["calculated_active_total"] = (
    registration_2024[
        active_registration_columns
    ].sum(axis=1)
)

registration_2024["active_total_difference"] = (
    registration_2024["calculated_active_total"]
    - registration_2024["active_total"]
)

active_2024_discrepancies = registration_2024.loc[
    registration_2024["active_total_difference"] != 0,
    [
        "county_name",
        "active_total",
        "calculated_active_total",
        "active_total_difference",
    ],
]

print(
    "Counties with active-total discrepancies:",
    len(active_2024_discrepancies)
)

active_2024_discrepancies

Counties with active-total discrepancies: 0

Empty DataFrame
Columns: [county_name, active_total, calculated_active_total, active_total_difference]
Index: []

In [ ]:
registration_2024["calculated_inactive_total"] = (
    registration_2024[
        inactive_registration_columns
    ].sum(axis=1)
)

registration_2024["inactive_total_difference"] = (
    registration_2024["calculated_inactive_total"]
    - registration_2024["inactive_total"]
)

inactive_2024_discrepancies = registration_2024.loc[
    registration_2024["inactive_total_difference"] != 0,
    [
        "county_name",
        "inactive_total",
        "calculated_inactive_total",
        "inactive_total_difference",
    ],
]

print(
    "Counties with inactive-total discrepancies:",
    len(inactive_2024_discrepancies)
)

inactive_2024_discrepancies

Counties with inactive-total discrepancies: 0

Empty DataFrame
Columns: [county_name, inactive_total, calculated_inactive_total, inactive_total_difference]
Index: []

In [ ]:
registration_2024["calculated_registered_total"] = (
    registration_2024["active_total"]
    + registration_2024["inactive_total"]
)

registration_2024["registered_total_difference"] = (
    registration_2024["calculated_registered_total"]
    - registration_2024["registered_total"]
)

overall_2024_discrepancies = registration_2024.loc[
    registration_2024["registered_total_difference"] != 0,
    [
        "county_name",
        "registered_total",
        "active_total",
        "inactive_total",
        "calculated_registered_total",
        "registered_total_difference",
    ],
]

print(
    "Counties with overall registration discrepancies:",
    len(overall_2024_discrepancies)
)

overall_2024_discrepancies

Counties with overall registration discrepancies: 0

Empty DataFrame
Columns: [county_name, registered_total, active_total, inactive_total, calculated_registered_total, registered_total_difference]
Index: []

In [ ]:
registration_2024 = registration_2024.drop(
    columns=[
        "calculated_active_total",
        "active_total_difference",
        "calculated_inactive_total",
        "inactive_total_difference",
        "calculated_registered_total",
        "registered_total_difference",
    ]
)



---

In [ ]:
registration_2024_output = (
    CLEAN_2024
    / "voter_registration_2024_clean.csv"
)

registration_2024.to_csv(
    registration_2024_output,
    index=False,
    encoding="utf-8",
)

print("Saved cleaned 2024 registration file to:")
print(registration_2024_output)

Saved cleaned 2024 registration file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2024/voter_registration_2024_clean.csv



---

# **Combining 2020 and 2024 Registration Data**

In [ ]:
registration_combined = pd.concat(
    [
        registration_2020,
        registration_2024,
    ],
    ignore_index=True,
)

registration_combined = (
    registration_combined.sort_values(
        ["county_name", "year"]
    )
    .reset_index(drop=True)
)

print(
    "Combined shape:",
    registration_combined.shape
)

registration_combined.head()

Combined shape: (86, 23)

,year,county_name,registered_total,active_asian,active_american_indian,active_black,active_federally_registered,active_hispanic,active_korean,active_white,...,inactive_asian,inactive_american_indian,inactive_black,inactive_federally_registered,inactive_hispanic,inactive_korean,inactive_white,inactive_other,inactive_not_identified,inactive_total
0,2020,Autauga,43482,269,89,7992,0,329,0,31619,...,27,20,501,0,35,0,1933,55,30,2601
1,2024,Autauga,46518,293,71,8588,0,443,0,32171,...,50,17,907,0,91,0,3182,62,71,4380
2,2020,Bibb,14992,11,29,2575,0,55,0,11627,...,3,4,152,0,2,0,478,2,0,641
3,2024,Bibb,15161,14,19,2507,0,77,0,11676,...,5,2,191,0,8,0,576,2,3,787
4,2020,Blount,41865,75,106,603,2,1083,1,38233,...,6,7,29,0,33,0,1382,20,7,1484

In [ ]:
registration_combined_duplicates = (
    registration_combined[
        registration_combined.duplicated(
            subset=["county_name", "year"],
            keep=False,
        )
    ]
)

print(
    "Duplicate county-year rows:",
    len(registration_combined_duplicates)
)

registration_combined_duplicates

Duplicate county-year rows: 0

Empty DataFrame
Columns: [year, county_name, registered_total, active_asian, active_american_indian, active_black, active_federally_registered, active_hispanic, active_korean, active_white, active_other, active_not_identified, active_total, inactive_asian, inactive_american_indian, inactive_black, inactive_federally_registered, inactive_hispanic, inactive_korean, inactive_white, inactive_other, inactive_not_identified, inactive_total]
Index: []

[0 rows x 23 columns]

In [ ]:
registration_combined.groupby(
    "year"
)["county_name"].nunique()

year
2020    43
2024    43
Name: county_name, dtype: int64

In [ ]:
registration_combined_output = (
    CLEAN_COMBINED
    / "voter_registration_clean.csv"
)

registration_combined.to_csv(
    registration_combined_output,
    index=False,
    encoding="utf-8",
)

print("Saved combined registration file to:")
print(registration_combined_output)

Saved combined registration file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/Combined/voter_registration_clean.csv



---

# **CVAP**



---

**2020 CVAP**

In [ ]:
cvap_2020_raw = pd.read_csv(
    RAW_2020 / "al_cvap_2020_cnty.csv"
)

print("Raw shape:", cvap_2020_raw.shape)
print("\nColumns:")
print(cvap_2020_raw.columns.tolist())

cvap_2020_raw.head()

Raw shape: (67, 110)

Columns:
['GEOID', 'NAME', 'STATE', 'COUNTY', 'C_TOT20', 'CTOTMOE', 'C_NHS20', 'CNHSMOE', 'C_AIA20', 'CAIAMOE', 'C_ASN20', 'CASNMOE', 'C_BLK20', 'CBLKMOE', 'C_NHP20', 'CNHPMOE', 'C_WHT20', 'CWHTMOE', 'C_AIW20', 'CAIWMOE', 'C_ASW20', 'CASWMOE', 'C_BLW20', 'CBLWMOE', 'C_AIB20', 'CAIBMOE', 'C_2OM20', 'C2OMMOE', 'C_HSP20', 'CHSPMOE', 'CVAP_TOT20', 'CVAPTOTMOE', 'CVAP_NHS20', 'CVAPNHSMOE', 'CVAP_AIA20', 'CVAPAIAMOE', 'CVAP_ASN20', 'CVAPASNMOE', 'CVAP_BLK20', 'CVAPBLKMOE', 'CVAP_NHP20', 'CVAPNHPMOE', 'CVAP_WHT20', 'CVAPWHTMOE', 'CVAP_AIW20', 'CVAPAIWMOE', 'CVAP_ASW20', 'CVAPASWMOE', 'CVAP_BLW20', 'CVAPBLWMOE', 'CVAP_AIB20', 'CVAPAIBMOE', 'CVAP_2OM20', 'CVAP2OMMOE', 'CVAP_HSP20', 'CVAPHSPMOE', 'ALL_TOT20', 'ALLTOTMOE', 'ALL_NHS20', 'ALLNHSMOE', 'ALL_AIA20', 'ALLAIAMOE', 'ALL_ASN20', 'ALLASNMOE', 'ALL_BLK20', 'ALLBLKMOE', 'ALL_NHP20', 'ALLNHPMOE', 'ALL_WHT20', 'ALLWHTMOE', 'ALL_AIW20', 'ALLAIWMOE', 'ALL_ASW20', 'ALLASWMOE', 'ALL_BLW20', 'ALLBLWMOE', 'ALL_AIB20', 'ALLAIBMOE', 'ALL_2OM20', 'ALL2OMMOE', 'ALL_HSP20', 'ALLHSPMOE', 'VAP_TOT20', 'VAPTOTMOE', 'VAP_NHS20', 'VAPNHSMOE', 'VAP_AIA20', 'VAPAIAMOE', 'VAP_ASN20', 'VAPASNMOE', 'VAP_BLK20', 'VAPBLKMOE', 'VAP_NHP20', 'VAPNHPMOE', 'VAP_WHT20', 'VAPWHTMOE', 'VAP_AIW20', 'VAPAIWMOE', 'VAP_ASW20', 'VAPASWMOE', 'VAP_BLW20', 'VAPBLWMOE', 'VAP_AIB20', 'VAPAIBMOE', 'VAP_2OM20', 'VAP2OMMOE', 'VAP_HSP20', 'VAPHSPMOE', 'STATEFP', 'COUNTYFP']

,GEOID,NAME,STATE,COUNTY,C_TOT20,CTOTMOE,C_NHS20,CNHSMOE,C_AIA20,CAIAMOE,...,VAP_BLW20,VAPBLWMOE,VAP_AIB20,VAPAIBMOE,VAP_2OM20,VAP2OMMOE,VAP_HSP20,VAPHSPMOE,STATEFP,COUNTYFP
0,1001,"Autauga County, Alabama",Alabama,Autauga County,54975,318,53610,257,450,145.88,...,175,155,20,26,95,108,1065,0,1,1
1,1003,"Baldwin County, Alabama",Alabama,Baldwin County,214510,601,206765,432,2865,533.75,...,205,180,75,98,580,444,6395,0,1,3
2,1005,"Barbour County, Alabama",Alabama,Barbour County,24635,115,23790,57,250,124.02,...,25,26,65,48,50,51,645,0,1,5
3,1007,"Bibb County, Alabama",Alabama,Bibb County,22165,67,21775,5,70,72.81,...,10,16,0,23,10,14,435,0,1,7
4,1009,"Blount County, Alabama",Alabama,Blount County,56320,324,52235,102,620,72.29,...,65,68,0,29,80,70,3300,0,1,9



---

**CLEANING:**


*   Kepy only CVAP_EST variables
*  renamed columns

*   add year
*   filter the needed countries

In [ ]:
cvap_2020 = cvap_2020_raw[
    [
        "COUNTY",
        "CVAP_TOT20",
        "CVAP_AIA20",
        "CVAP_ASN20",
        "CVAP_BLK20",
        "CVAP_WHT20",
        "CVAP_2OM20",
        "CVAP_HSP20",
    ]
].copy()

print("Selected shape:", cvap_2020.shape)

cvap_2020.head()

Selected shape: (67, 8)

,COUNTY,CVAP_TOT20,CVAP_AIA20,CVAP_ASN20,CVAP_BLK20,CVAP_WHT20,CVAP_2OM20,CVAP_HSP20
0,Autauga County,41960,395,530,8135,31990,95,840
1,Baldwin County,167985,2260,1540,14245,144995,570,4435
2,Barbour County,19470,220,45,9245,9565,50,405
3,Bibb County,17585,70,59,4000,13220,10,230
4,Blount County,42980,505,80,610,39595,80,2050

In [ ]:
cvap_2020 = cvap_2020.rename(
    columns={
        "COUNTY": "county_name",
        "CVAP_TOT20": "cvap_est_total",
        "CVAP_AIA20": "cvap_est_american_indian",
        "CVAP_ASN20": "cvap_est_asian",
        "CVAP_BLK20": "cvap_est_black",
        "CVAP_WHT20": "cvap_est_white",
        "CVAP_2OM20": "cvap_est_two_or_more",
        "CVAP_HSP20": "cvap_est_hispanic",
    }
)

cvap_2020.head()

,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,Autauga County,41960,395,530,8135,31990,95,840
1,Baldwin County,167985,2260,1540,14245,144995,570,4435
2,Barbour County,19470,220,45,9245,9565,50,405
3,Bibb County,17585,70,59,4000,13220,10,230
4,Blount County,42980,505,80,610,39595,80,2050

In [ ]:
cvap_2020["county_name"] = (
    cvap_2020["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)

    .str.replace(
        r"\s+County$",
        "",
        regex=True,
        case=False
    )

    .str.lower()
    .str.title()
)

cvap_2020["county_name"] = (
    cvap_2020["county_name"].replace(
        {
            "Dekalb": "DeKalb",
            "St Clair": "St. Clair",
        }
    )
)

print(
    cvap_2020["county_name"].head(10).tolist()
)

['Autauga', 'Baldwin', 'Barbour', 'Bibb', 'Blount', 'Bullock', 'Butler', 'Calhoun', 'Chambers', 'Cherokee']

In [ ]:
cvap_2020.insert(
    0,
    "year",
    2020
)

cvap_2020.head()

,year,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,2020,Autauga,41960,395,530,8135,31990,95,840
1,2020,Baldwin,167985,2260,1540,14245,144995,570,4435
2,2020,Barbour,19470,220,45,9245,9565,50,405
3,2020,Bibb,17585,70,59,4000,13220,10,230
4,2020,Blount,42980,505,80,610,39595,80,2050

In [ ]:
cvap_numeric_columns = [
    "cvap_est_total",
    "cvap_est_american_indian",
    "cvap_est_asian",
    "cvap_est_black",
    "cvap_est_white",
    "cvap_est_two_or_more",
    "cvap_est_hispanic",
]

for column in cvap_numeric_columns:
    cvap_2020[column] = clean_numeric_column(
        cvap_2020[column]
    )

print(cvap_2020.dtypes)

year                                 int64
county_name                 string[python]
cvap_est_total                       Int64
cvap_est_american_indian             Int64
cvap_est_asian                       Int64
cvap_est_black                       Int64
cvap_est_white                       Int64
cvap_est_two_or_more                 Int64
cvap_est_hispanic                    Int64
dtype: object

In [ ]:
cvap_2020 = cvap_2020[
    cvap_2020["county_name"].isin(
        PROJECT_COUNTIES
    )
].copy()

cvap_2020 = (
    cvap_2020
    .sort_values("county_name")
    .reset_index(drop=True)
)

print("Cleaned shape:", cvap_2020.shape)

cvap_2020.head()

Cleaned shape: (43, 9)

,year,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,2020,Autauga,41960,395,530,8135,31990,95,840
1,2020,Bibb,17585,70,59,4000,13220,10,230
2,2020,Blount,42980,505,80,610,39595,80,2050
3,2020,Calhoun,88120,875,650,18140,66130,215,1845
4,2020,Chambers,26115,170,135,10330,15135,0,335



---

**Checking**

In [ ]:
cvap_2020_counties_found = set(
    cvap_2020["county_name"]
)

cvap_2020_missing_counties = sorted(
    set(PROJECT_COUNTIES)
    - cvap_2020_counties_found
)

cvap_2020_unexpected_counties = sorted(
    cvap_2020_counties_found
    - set(PROJECT_COUNTIES)
)

print(
    "Missing counties:",
    cvap_2020_missing_counties
)

print(
    "Unexpected counties:",
    cvap_2020_unexpected_counties
)

Missing counties: []
Unexpected counties: []

In [ ]:
cvap_2020_duplicates = cvap_2020[
    cvap_2020.duplicated(
        subset=["year", "county_name"],
        keep=False
    )
]

print(
    "Number of duplicate rows:",
    len(cvap_2020_duplicates)
)

cvap_2020_duplicates

Number of duplicate rows: 0

Empty DataFrame
Columns: [year, county_name, cvap_est_total, cvap_est_american_indian, cvap_est_asian, cvap_est_black, cvap_est_white, cvap_est_two_or_more, cvap_est_hispanic]
Index: []

In [ ]:
print(
    cvap_2020.isna().sum()
)

year                        0
county_name                 0
cvap_est_total              0
cvap_est_american_indian    0
cvap_est_asian              0
cvap_est_black              0
cvap_est_white              0
cvap_est_two_or_more        0
cvap_est_hispanic           0
dtype: int64

In [ ]:
cvap_2020_negative_values = cvap_2020[
    (cvap_2020[cvap_numeric_columns] < 0)
    .any(axis=1)
]

print(
    "Rows containing negative CVAP values:",
    len(cvap_2020_negative_values)
)

cvap_2020_negative_values

Rows containing negative CVAP values: 0

Empty DataFrame
Columns: [year, county_name, cvap_est_total, cvap_est_american_indian, cvap_est_asian, cvap_est_black, cvap_est_white, cvap_est_two_or_more, cvap_est_hispanic]
Index: []

In [ ]:
cvap_demographic_columns = [
    "cvap_est_american_indian",
    "cvap_est_asian",
    "cvap_est_black",
    "cvap_est_white",
    "cvap_est_two_or_more",
    "cvap_est_hispanic",
]

cvap_2020_exceeds_total = cvap_2020[
    cvap_2020[cvap_demographic_columns]
    .gt(
        cvap_2020["cvap_est_total"],
        axis=0
    )
    .any(axis=1)
]

print(
    "Rows where an individual demographic estimate exceeds total CVAP:",
    len(cvap_2020_exceeds_total)
)

cvap_2020_exceeds_total

Rows where an individual demographic estimate exceeds total CVAP: 0

Empty DataFrame
Columns: [year, county_name, cvap_est_total, cvap_est_american_indian, cvap_est_asian, cvap_est_black, cvap_est_white, cvap_est_two_or_more, cvap_est_hispanic]
Index: []

In [ ]:
print("Final shape:", cvap_2020.shape)

print("\nFinal columns:")
print(cvap_2020.columns.tolist())

cvap_2020.head(10)

Final shape: (43, 9)

Final columns:
['year', 'county_name', 'cvap_est_total', 'cvap_est_american_indian', 'cvap_est_asian', 'cvap_est_black', 'cvap_est_white', 'cvap_est_two_or_more', 'cvap_est_hispanic']

,year,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,2020,Autauga,41960,395,530,8135,31990,95,840
1,2020,Bibb,17585,70,59,4000,13220,10,230
2,2020,Blount,42980,505,80,610,39595,80,2050
3,2020,Calhoun,88120,875,650,18140,66130,215,1845
4,2020,Chambers,26115,170,135,10330,15135,0,335
5,2020,Cherokee,20670,305,29,990,19210,0,140
6,2020,Chilton,32450,95,85,3580,27725,45,970
7,2020,Clay,10435,8,25,1583,8650,0,180
8,2020,Cleburne,11445,120,35,390,10770,4,125
9,2020,Coffee,38935,930,430,7035,28515,55,2105



---

In [ ]:
cvap_2020_output = (
    CLEAN_2020
    / "cvap_2020_clean.csv"
)

cvap_2020.to_csv(
    cvap_2020_output,
    index=False,
    encoding="utf-8"
)

print("Saved cleaned 2020 CVAP file to:")
print(cvap_2020_output)

Saved cleaned 2020 CVAP file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2020/cvap_2020_clean.csv

In [ ]:
cvap_2020_check = pd.read_csv(
    cvap_2020_output
)

print(
    "Saved file shape:",
    cvap_2020_check.shape
)

print("\nSaved columns:")
print(cvap_2020_check.columns.tolist())

cvap_2020_check.head()

Saved file shape: (43, 9)

Saved columns:
['year', 'county_name', 'cvap_est_total', 'cvap_est_american_indian', 'cvap_est_asian', 'cvap_est_black', 'cvap_est_white', 'cvap_est_two_or_more', 'cvap_est_hispanic']

,year,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,2020,Autauga,41960,395,530,8135,31990,95,840
1,2020,Bibb,17585,70,59,4000,13220,10,230
2,2020,Blount,42980,505,80,610,39595,80,2050
3,2020,Calhoun,88120,875,650,18140,66130,215,1845
4,2020,Chambers,26115,170,135,10330,15135,0,335



---

**2024 CVAP**

In [ ]:
cvap_2024_raw = pd.read_csv(
    RAW_2024 / "al_cvap_2024_cnty.csv"
)

print("Raw shape:", cvap_2024_raw.shape)

print("\nColumns:")
print(cvap_2024_raw.columns.tolist())

cvap_2024_raw.head()

Raw shape: (67, 70)

Columns:
['GEOID', 'NAME', 'STATE', 'COUNTY', 'STATEFP', 'COUNTYFP', 'C_TOT24', 'CTOTMOE', 'C_NHS24', 'CNHSMOE', 'C_AMI24', 'CAMIMOE', 'C_ASI24', 'CASIMOE', 'C_BLA24', 'CBLAMOE', 'C_NHP24', 'CNHPMOE', 'C_WHT24', 'CWHTMOE', 'C_AIW24', 'CAIWMOE', 'C_ASW24', 'CASWMOE', 'C_BLW24', 'CBLWMOE', 'C_AIB24', 'CAIBMOE', 'C_2OM24', 'C2OMMOE', 'C_HSP24', 'CHSPMOE', 'C_AIA24', 'CAIAMOE', 'C_ASN24', 'CASNMOE', 'C_BLK24', 'CBLKMOE', 'CVAP_TOT24', 'CVAPTOTMOE', 'CVAP_NHS24', 'CVAPNHSMOE', 'CVAP_AMI24', 'CVAPAMIMOE', 'CVAP_ASI24', 'CVAPASIMOE', 'CVAP_BLA24', 'CVAPBLAMOE', 'CVAP_NHP24', 'CVAPNHPMOE', 'CVAP_WHT24', 'CVAPWHTMOE', 'CVAP_AIW24', 'CVAPAIWMOE', 'CVAP_ASW24', 'CVAPASWMOE', 'CVAP_BLW24', 'CVAPBLWMOE', 'CVAP_AIB24', 'CVAPAIBMOE', 'CVAP_2OM24', 'CVAP2OMMOE', 'CVAP_HSP24', 'CVAPHSPMOE', 'CVAP_AIA24', 'CVAPAIAMOE', 'CVAP_ASN24', 'CVAPASNMOE', 'CVAP_BLK24', 'CVAPBLKMOE']

,GEOID,NAME,STATE,COUNTY,STATEFP,COUNTYFP,C_TOT24,CTOTMOE,C_NHS24,CNHSMOE,...,CVAP_2OM24,CVAP2OMMOE,CVAP_HSP24,CVAPHSPMOE,CVAP_AIA24,CVAPAIAMOE,CVAP_ASN24,CVAPASNMOE,CVAP_BLK24,CVAPBLKMOE
0,1001,"Autauga County, Alabama",Alabama,Autauga County,1,1,59123,351,57173,322,...,113,111,1199,183,422,60.07,639,217.15,9392,324.96
1,1003,"Baldwin County, Alabama",Alabama,Baldwin County,1,3,241558,1063,230113,660,...,472,417,6809,605,2528,233.59,2214,347.88,15460,591.79
2,1005,"Barbour County, Alabama",Alabama,Barbour County,1,5,24043,143,23025,35,...,54,78,444,104,168,43.75,61,18.44,9002,97.67
3,1007,"Bibb County, Alabama",Alabama,Bibb County,1,7,21763,118,21321,42,...,9,18,199,106,158,39.41,210,197.39,3668,238.62
4,1009,"Blount County, Alabama",Alabama,Blount County,1,9,57584,303,53246,101,...,88,66,2218,270,585,80.85,122,84.88,744,131.66



---

In [ ]:
cvap_2024 = cvap_2024_raw[
    [
        "COUNTY",
        "CVAP_TOT24",
        "CVAP_AIA24",
        "CVAP_ASN24",
        "CVAP_BLK24",
        "CVAP_WHT24",
        "CVAP_2OM24",
        "CVAP_HSP24",
    ]
].copy()

print("Selected shape:", cvap_2024.shape)

cvap_2024.head()

Selected shape: (67, 8)

,COUNTY,CVAP_TOT24,CVAP_AIA24,CVAP_ASN24,CVAP_BLK24,CVAP_WHT24,CVAP_2OM24,CVAP_HSP24
0,Autauga County,45205,422,639,9392,33452,113,1199
1,Baldwin County,190329,2528,2214,15460,162778,472,6809
2,Barbour County,19026,168,61,9002,9301,54,444
3,Bibb County,17349,158,210,3668,13105,9,199
4,Blount County,43938,585,122,744,40154,88,2218

In [ ]:
cvap_2024 = cvap_2024.rename(
    columns={
        "COUNTY": "county_name",
        "CVAP_TOT24": "cvap_est_total",
        "CVAP_AIA24": "cvap_est_american_indian",
        "CVAP_ASN24": "cvap_est_asian",
        "CVAP_BLK24": "cvap_est_black",
        "CVAP_WHT24": "cvap_est_white",
        "CVAP_2OM24": "cvap_est_two_or_more",
        "CVAP_HSP24": "cvap_est_hispanic",
    }
)

cvap_2024.head()

,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,Autauga County,45205,422,639,9392,33452,113,1199
1,Baldwin County,190329,2528,2214,15460,162778,472,6809
2,Barbour County,19026,168,61,9002,9301,54,444
3,Bibb County,17349,158,210,3668,13105,9,199
4,Blount County,43938,585,122,744,40154,88,2218

In [ ]:
cvap_2024["county_name"] = (
    cvap_2024["county_name"]
    .astype("string")
    .str.strip()
    .str.replace("_", " ", regex=False)

    .str.replace(
        r"\s+County$",
        "",
        regex=True,
        case=False
    )

    .str.lower()
    .str.title()
)

cvap_2024["county_name"] = (
    cvap_2024["county_name"].replace(
        {
            "Dekalb": "DeKalb",
            "St Clair": "St. Clair",
        }
    )
)

print(
    cvap_2024["county_name"].head(10).tolist()
)

['Autauga', 'Baldwin', 'Barbour', 'Bibb', 'Blount', 'Bullock', 'Butler', 'Calhoun', 'Chambers', 'Cherokee']

In [ ]:
cvap_2024.insert(
    0,
    "year",
    2024
)

cvap_2024.head()

,year,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,2024,Autauga,45205,422,639,9392,33452,113,1199
1,2024,Baldwin,190329,2528,2214,15460,162778,472,6809
2,2024,Barbour,19026,168,61,9002,9301,54,444
3,2024,Bibb,17349,158,210,3668,13105,9,199
4,2024,Blount,43938,585,122,744,40154,88,2218

In [ ]:
cvap_numeric_columns = [
    "cvap_est_total",
    "cvap_est_american_indian",
    "cvap_est_asian",
    "cvap_est_black",
    "cvap_est_white",
    "cvap_est_two_or_more",
    "cvap_est_hispanic",
]

for column in cvap_numeric_columns:
    cvap_2024[column] = clean_numeric_column(
        cvap_2024[column]
    )

print(cvap_2024.dtypes)

year                                 int64
county_name                 string[python]
cvap_est_total                       Int64
cvap_est_american_indian             Int64
cvap_est_asian                       Int64
cvap_est_black                       Int64
cvap_est_white                       Int64
cvap_est_two_or_more                 Int64
cvap_est_hispanic                    Int64
dtype: object

In [ ]:
cvap_2024 = cvap_2024[
    cvap_2024["county_name"].isin(
        PROJECT_COUNTIES
    )
].copy()

cvap_2024 = (
    cvap_2024
    .sort_values("county_name")
    .reset_index(drop=True)
)

print("Cleaned shape:", cvap_2024.shape)

cvap_2024.head()

Cleaned shape: (43, 9)

,year,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,2024,Autauga,45205,422,639,9392,33452,113,1199
1,2024,Bibb,17349,158,210,3668,13105,9,199
2,2024,Blount,43938,585,122,744,40154,88,2218
3,2024,Calhoun,89451,842,843,19881,65598,152,2077
4,2024,Chambers,26687,621,48,10256,15290,63,428

In [ ]:
cvap_2024_counties_found = set(
    cvap_2024["county_name"]
)

cvap_2024_missing_counties = sorted(
    set(PROJECT_COUNTIES)
    - cvap_2024_counties_found
)

cvap_2024_unexpected_counties = sorted(
    cvap_2024_counties_found
    - set(PROJECT_COUNTIES)
)

print(
    "Missing counties:",
    cvap_2024_missing_counties
)

print(
    "Unexpected counties:",
    cvap_2024_unexpected_counties
)

Missing counties: []
Unexpected counties: []

In [ ]:
cvap_2024_duplicates = cvap_2024[
    cvap_2024.duplicated(
        subset=["year", "county_name"],
        keep=False
    )
]

print(
    "Number of duplicate rows:",
    len(cvap_2024_duplicates)
)

cvap_2024_duplicates

Number of duplicate rows: 0

Empty DataFrame
Columns: [year, county_name, cvap_est_total, cvap_est_american_indian, cvap_est_asian, cvap_est_black, cvap_est_white, cvap_est_two_or_more, cvap_est_hispanic]
Index: []

In [ ]:
print(
    cvap_2024.isna().sum()
)

year                        0
county_name                 0
cvap_est_total              0
cvap_est_american_indian    0
cvap_est_asian              0
cvap_est_black              0
cvap_est_white              0
cvap_est_two_or_more        0
cvap_est_hispanic           0
dtype: int64

In [ ]:
cvap_2024_negative_values = cvap_2024[
    (cvap_2024[cvap_numeric_columns] < 0)
    .any(axis=1)
]

print(
    "Rows containing negative CVAP values:",
    len(cvap_2024_negative_values)
)

cvap_2024_negative_values

Rows containing negative CVAP values: 0

Empty DataFrame
Columns: [year, county_name, cvap_est_total, cvap_est_american_indian, cvap_est_asian, cvap_est_black, cvap_est_white, cvap_est_two_or_more, cvap_est_hispanic]
Index: []

In [ ]:
cvap_demographic_columns = [
    "cvap_est_american_indian",
    "cvap_est_asian",
    "cvap_est_black",
    "cvap_est_white",
    "cvap_est_two_or_more",
    "cvap_est_hispanic",
]

cvap_2024_exceeds_total = cvap_2024[
    cvap_2024[cvap_demographic_columns]
    .gt(
        cvap_2024["cvap_est_total"],
        axis=0
    )
    .any(axis=1)
]

print(
    "Rows where an individual demographic estimate exceeds total CVAP:",
    len(cvap_2024_exceeds_total)
)

cvap_2024_exceeds_total

Rows where an individual demographic estimate exceeds total CVAP: 0

Empty DataFrame
Columns: [year, county_name, cvap_est_total, cvap_est_american_indian, cvap_est_asian, cvap_est_black, cvap_est_white, cvap_est_two_or_more, cvap_est_hispanic]
Index: []

In [ ]:
print("Final shape:", cvap_2024.shape)

print("\nFinal columns:")
print(cvap_2024.columns.tolist())

cvap_2024.head(10)

Final shape: (43, 9)

Final columns:
['year', 'county_name', 'cvap_est_total', 'cvap_est_american_indian', 'cvap_est_asian', 'cvap_est_black', 'cvap_est_white', 'cvap_est_two_or_more', 'cvap_est_hispanic']

,year,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,2024,Autauga,45205,422,639,9392,33452,113,1199
1,2024,Bibb,17349,158,210,3668,13105,9,199
2,2024,Blount,43938,585,122,744,40154,88,2218
3,2024,Calhoun,89451,842,843,19881,65598,152,2077
4,2024,Chambers,26687,621,48,10256,15290,63,428
5,2024,Cherokee,20400,323,38,1015,18787,6,243
6,2024,Chilton,33573,258,200,3511,28061,0,1541
7,2024,Clay,11167,102,22,1539,9180,19,299
8,2024,Cleburne,11986,100,17,563,11101,53,155
9,2024,Coffee,40299,843,761,7082,29056,130,2458



---

In [ ]:
cvap_2024_output = (
    CLEAN_2024
    / "cvap_2024_clean.csv"
)

cvap_2024.to_csv(
    cvap_2024_output,
    index=False,
    encoding="utf-8"
)

print("Saved cleaned 2024 CVAP file to:")
print(cvap_2024_output)

Saved cleaned 2024 CVAP file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/2024/cvap_2024_clean.csv



---

# **COMBINING 2020 AND 2024 CVAP DATA**

In [ ]:
cvap_combined = pd.concat(
    [
        cvap_2020,
        cvap_2024,
    ],
    ignore_index=True
)

cvap_combined = (
    cvap_combined
    .sort_values(
        ["county_name", "year"]
    )
    .reset_index(drop=True)
)

print(
    "Combined shape:",
    cvap_combined.shape
)

cvap_combined.head()

Combined shape: (86, 9)

,year,county_name,cvap_est_total,cvap_est_american_indian,cvap_est_asian,cvap_est_black,cvap_est_white,cvap_est_two_or_more,cvap_est_hispanic
0,2020,Autauga,41960,395,530,8135,31990,95,840
1,2024,Autauga,45205,422,639,9392,33452,113,1199
2,2020,Bibb,17585,70,59,4000,13220,10,230
3,2024,Bibb,17349,158,210,3668,13105,9,199
4,2020,Blount,42980,505,80,610,39595,80,2050

In [ ]:
print(
    "2020 and 2024 columns match:",
    cvap_2020.columns.tolist()
    == cvap_2024.columns.tolist()
)

2020 and 2024 columns match: True

In [ ]:
cvap_combined_duplicates = cvap_combined[
    cvap_combined.duplicated(
        subset=["year", "county_name"],
        keep=False
    )
]

print(
    "Duplicate county-year rows:",
    len(cvap_combined_duplicates)
)

cvap_combined_duplicates

Duplicate county-year rows: 0

Empty DataFrame
Columns: [year, county_name, cvap_est_total, cvap_est_american_indian, cvap_est_asian, cvap_est_black, cvap_est_white, cvap_est_two_or_more, cvap_est_hispanic]
Index: []

In [ ]:
cvap_combined.groupby(
    "year"
)["county_name"].nunique()

year
2020    43
2024    43
Name: county_name, dtype: int64

In [ ]:
print(
    cvap_combined.isna().sum()
)

year                        0
county_name                 0
cvap_est_total              0
cvap_est_american_indian    0
cvap_est_asian              0
cvap_est_black              0
cvap_est_white              0
cvap_est_two_or_more        0
cvap_est_hispanic           0
dtype: int64

In [ ]:
cvap_combined_output = (
    CLEAN_COMBINED
    / "cvap_clean.csv"
)

cvap_combined.to_csv(
    cvap_combined_output,
    index=False,
    encoding="utf-8"
)

print("Saved combined CVAP file to:")
print(cvap_combined_output)

Saved combined CVAP file to:
/content/drive/MyDrive/AL-VOTE DATA FOLDER/02_Cleaned_Data/Combined/cvap_clean.csv



---

# **PRECINCT LEVEL ELECTION DATA**

In [ ]:
election_files_2020 = sorted(
    RAW_2020.glob(
        "2020-General-*.xls"
    )
)

election_files_2024 = sorted(
    RAW_2024.glob(
        "2024-General-*.xls"
    )
)

print(
    "Number of 2020 election files:",
    len(election_files_2020)
)

print(
    "Number of 2024 election files:",
    len(election_files_2024)
)

Number of 2020 election files: 43
Number of 2024 election files: 43

In [ ]:
print("2020 election files:\n")

for file in election_files_2020:
    print(file.name)

print("\n2024 election files:\n")

for file in election_files_2024:
    print(file.name)

2020 election files:

2020-General-Autauga.xls
2020-General-Bibb.xls
2020-General-Blount.xls
2020-General-Calhoun.xls
2020-General-Chambers.xls
2020-General-Cherokee.xls
2020-General-Chilton.xls
2020-General-Clay.xls
2020-General-Cleburne.xls
2020-General-Coffee.xls
2020-General-Colbert.xls
2020-General-Coosa.xls
2020-General-Covington.xls
2020-General-Cullman.xls
2020-General-Dale.xls
2020-General-DeKalb.xls
2020-General-Elmore.xls
2020-General-Etowah.xls
2020-General-Fayette.xls
2020-General-Franklin.xls
2020-General-Geneva.xls
2020-General-Henry.xls
2020-General-Houston.xls
2020-General-Jackson.xls
2020-General-Jefferson.xls
2020-General-Lamar.xls
2020-General-Lauderdale.xls
2020-General-Lawrence.xls
2020-General-Lee.xls
2020-General-Limestone.xls
2020-General-Madison.xls
2020-General-Marion.xls
2020-General-Marshall.xls
2020-General-Morgan.xls
2020-General-Pickens.xls
2020-General-Randolph.xls
2020-General-Shelby.xls
2020-General-StClair.xls
2020-General-Talladega.xls
2020-General-Tallapoosa.xls
2020-General-Tuscaloosa.xls
2020-General-Walker.xls
2020-General-Winston.xls

2024 election files:

2024-General-Autauga.xls
2024-General-Bibb.xls
2024-General-Blount.xls
2024-General-Calhoun.xls
2024-General-Chambers.xls
2024-General-Cherokee.xls
2024-General-Chilton.xls
2024-General-Clay.xls
2024-General-Cleburne.xls
2024-General-Coffee.xls
2024-General-Colbert.xls
2024-General-Coosa.xls
2024-General-Covington.xls
2024-General-Cullman.xls
2024-General-Dale.xls
2024-General-DeKalb.xls
2024-General-Elmore.xls
2024-General-Etowah.xls
2024-General-Fayette.xls
2024-General-Franklin.xls
2024-General-Geneva.xls
2024-General-Henry.xls
2024-General-Houston.xls
2024-General-Jackson.xls
2024-General-Jefferson.xls
2024-General-Lamar.xls
2024-General-Lauderdale.xls
2024-General-Lawrence.xls
2024-General-Lee.xls
2024-General-Limestone.xls
2024-General-Madison.xls
2024-General-Marion.xls
2024-General-Marshall.xls
2024-General-Morgan.xls
2024-General-Pickens.xls
2024-General-Randolph.xls
2024-General-Shelby.xls
2024-General-StClair.xls
2024-General-Talladega.xls
2024-General-Tallapoosa.xls
2024-General-Tuscaloosa.xls
2024-General-Walker.xls
2024-General-Winston.xls



---

**Needed county name function**


*   extracts and standardizes the county name from the files
* removes the year and general
* removes spaces
* standardizes the capitialization
* corrects the special names

In [ ]:
def extract_county_from_filename(file_path):

    county_name = file_path.stem

    county_name = re.sub(
        r"^\d{4}[-_\s]+General[-_\s]+",
        "",
        county_name,
        flags=re.IGNORECASE
    )

    county_name = re.sub(
        r"\(\d+\)$",
        "",
        county_name
    )

    county_name = county_name.replace("_", " ")
    county_name = county_name.replace("-", " ")


    county_name = re.sub(
        r"\s+",
        " ",
        county_name
    ).strip()

    county_name = county_name.lower().title()

    county_name = {
        "Dekalb": "DeKalb",
        "St Clair": "St. Clair",
        "St. Clair": "St. Clair",
        "Stclair": "St. Clair",
    }.get(
        county_name,
        county_name
    )

    return county_name



---

**Testing to make sure function works and if all data can be read**

In [ ]:
PROJECT_COUNTIES = [
    "Autauga",
    "Bibb",
    "Blount",
    "Calhoun",
    "Chambers",
    "Cherokee",
    "Chilton",
    "Clay",
    "Cleburne",
    "Coffee",
    "Colbert",
    "Coosa",
    "Covington",
    "Cullman",
    "Dale",
    "DeKalb",
    "Elmore",
    "Etowah",
    "Fayette",
    "Franklin",
    "Geneva",
    "Henry",
    "Houston",
    "Jackson",
    "Jefferson",
    "Lamar",
    "Lauderdale",
    "Lawrence",
    "Lee",
    "Limestone",
    "Madison",
    "Marion",
    "Marshall",
    "Morgan",
    "Pickens",
    "Randolph",
    "Shelby",
    "St. Clair",
    "Talladega",
    "Tallapoosa",
    "Tuscaloosa",
    "Walker",
    "Winston",
]

In [ ]:
election_counties_2020 = [
    extract_county_from_filename(file)
    for file in election_files_2020
]

election_counties_2024 = [
    extract_county_from_filename(file)
    for file in election_files_2024
]

In [ ]:
missing_counties_2020 = sorted(
    set(PROJECT_COUNTIES)
    - set(election_counties_2020)
)

unexpected_counties_2020 = sorted(
    set(election_counties_2020)
    - set(PROJECT_COUNTIES)
)

missing_counties_2024 = sorted(
    set(PROJECT_COUNTIES)
    - set(election_counties_2024)
)

unexpected_counties_2024 = sorted(
    set(election_counties_2024)
    - set(PROJECT_COUNTIES)
)

print("2020 missing counties:")
print(missing_counties_2020)

print("\n2020 unexpected counties:")
print(unexpected_counties_2020)

print("\n2024 missing counties:")
print(missing_counties_2024)

print("\n2024 unexpected counties:")
print(unexpected_counties_2024)

2020 missing counties:
[]

2020 unexpected counties:
[]

2024 missing counties:
[]

2024 unexpected counties:
[]

In [ ]:
print(
    "Files successfully read:",
    election_inspection_2020[
        "read_successfully"
    ].sum()
)

print(
    "Files that failed:",
    (
        ~election_inspection_2020[
            "read_successfully"
        ]
    ).sum()
)

print("\nSmallest row count:")
print(
    election_inspection_2020[
        "row_count"
    ].min()
)

print("\nLargest row count:")
print(
    election_inspection_2020[
        "row_count"
    ].max()
)

print("\nSmallest column count:")
print(
    election_inspection_2020[
        "column_count"
    ].min()
)

print("\nLargest column count:")
print(
    election_inspection_2020[
        "column_count"
    ].max()
)

NameError: name 'election_inspection_2020' is not defined

In [ ]:
print(
    "Files successfully read:",
    election_inspection_2024[
        "read_successfully"
    ].sum()
)

print(
    "Files that failed:",
    (
        ~election_inspection_2024[
            "read_successfully"
        ]
    ).sum()
)

print("\nSmallest row count:")
print(
    election_inspection_2024[
        "row_count"
    ].min()
)

print("\nLargest row count:")
print(
    election_inspection_2024[
        "row_count"
    ].max()
)

print("\nSmallest column count:")
print(
    election_inspection_2024[
        "column_count"
    ].min()
)

print("\nLargest column count:")
print(
    election_inspection_2024[
        "column_count"
    ].max()
)



---

**Importer Function**


*   extrats the country name
* identifies precinct and voting method columns
* converts into numeric values
* sums into total votes
* standardizes

In [ ]:
def import_county_election_file(
    file_path,
    year
):

    df = pd.read_excel(
        file_path,
        engine="xlrd"
    )

    county_name = (
        extract_county_from_filename(
            file_path
        )
    )

    required_columns = [
        "Contest Title",
        "Party",
        "Candidate",
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing_columns:
        raise ValueError(
            f"{file_path.name} is missing "
            f"required columns: {missing_columns}"
        )
    vote_columns = [
        column
        for column in df.columns
        if column not in required_columns
    ]

    for column in vote_columns:
        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

    df["total_votes"] = (
        df[vote_columns]
        .sum(
            axis=1,
            min_count=1
        )
    )

    df.insert(
        0,
        "year",
        year
    )

    df.insert(
        1,
        "county_name",
        county_name
    )

    df["source_file"] = file_path.name

    df = df[
        [
            "year",
            "county_name",
            "Contest Title",
            "Party",
            "Candidate",
            "total_votes",
            "source_file",
        ]
    ].copy()

    df = df.rename(
        columns={
            "Contest Title": "contest_title",
            "Party": "party",
            "Candidate": "candidate",
        }
    )

    return df



---

**Combining all 43 counties for 2020 and 2024**

In [ ]:
election_2020_parts = []

for file in election_files_2020:

    county_data = (
        import_county_election_file(
            file,
            2020
        )
    )

    election_2020_parts.append(
        county_data
    )

election_2020_combined_raw = pd.concat(
    election_2020_parts,
    ignore_index=True
)

print(
    "Combined 2020 shape:",
    election_2020_combined_raw.shape
)

print(
    "Number of 2020 counties:",
    election_2020_combined_raw[
        "county_name"
    ].nunique()
)

election_2020_combined_raw.head()

In [ ]:
election_2024_parts = []

for file in election_files_2024:

    county_data = (
        import_county_election_file(
            file,
            2024
        )
    )

    election_2024_parts.append(
        county_data
    )

election_2024_combined_raw = pd.concat(
    election_2024_parts,
    ignore_index=True
)

print(
    "Combined 2024 shape:",
    election_2024_combined_raw.shape
)

print(
    "Number of 2024 counties:",
    election_2024_combined_raw[
        "county_name"
    ].nunique()
)

election_2024_combined_raw.head()

CHECKING

In [ ]:
print("2020 unique counties:")
print(
    election_2020_combined_raw[
        "county_name"
    ].nunique()
)

print("\n2024 unique counties:")
print(
    election_2024_combined_raw[
        "county_name"
    ].nunique()
)

In [ ]:
print("2020 missing total_votes:")
print(
    election_2020_combined_raw[
        "total_votes"
    ].isna().sum()
)

print("\n2024 missing total_votes:")
print(
    election_2024_combined_raw[
        "total_votes"
    ].isna().sum()
)



---

# **CLEANING**
* fixed spacing
* filtered contests
* removed blank rows

In [ ]:
election_2020_combined_raw
election_2024_combined_raw

Text Cleaning function

In [ ]:
def clean_election_text(series):
    return (
        series
        .astype("string")
        .str.strip()
        .str.replace(
            r"\s+",
            " ",
            regex=True
        )
        .replace(
            {
                "": pd.NA,
                "nan": pd.NA,
                "<NA>": pd.NA,
            }
        )
    )

Election Cleaning Function:


*  makes total_votes numberic
*   removes negative totals
* keeps the needed contests
* standardizes the contest type

In [ ]:
def clean_combined_election_data(
    combined_raw
):

    df = combined_raw.copy()

    text_columns = [
        "county_name",
        "contest_title",
        "party",
        "candidate",
        "source_file",
    ]

    for column in text_columns:
        df[column] = clean_election_text(
            df[column]
        )

    df["total_votes"] = pd.to_numeric(
        df["total_votes"],
        errors="coerce"
    ).round().astype("Int64")

    df = df[
        df["county_name"].notna()
        & df["contest_title"].notna()
        & df["candidate"].notna()
        & df["total_votes"].notna()
    ].copy()

    df = df[
        df["total_votes"] >= 0
    ].copy()

    presidential_mask = (
        df["contest_title"]
        == "PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES"
    )

    congressional_mask = (
        df["contest_title"]
        .str.startswith(
            "UNITED STATES REPRESENTATIVE",
            na=False
        )
    )

    df = df[
        presidential_mask
        | congressional_mask
    ].copy()

    df["contest_type"] = pd.NA

    df.loc[
        df["contest_title"]
        == "PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES",
        "contest_type"
    ] = "president"

    df.loc[
        df["contest_title"]
        .str.startswith(
            "UNITED STATES REPRESENTATIVE",
            na=False
        ),
        "contest_type"
    ] = "us_house"

    df["district_number"] = (
        df["contest_title"]
        .str.extract(
            r"(\d+)(?:ST|ND|RD|TH)\s+CONGRESSIONAL",
            expand=False
        )
    )

    df["district_number"] = pd.to_numeric(
        df["district_number"],
        errors="coerce"
    ).astype("Int64")

    df.loc[
        df["contest_type"] == "president",
        "district_number"
    ] = pd.NA

    candidate_lower = (
        df["candidate"]
        .astype("string")
        .str.lower()
    )

    df["result_type"] = "candidate"

    df.loc[
        candidate_lower == "write-in",
        "result_type"
    ] = "write_in"

    df.loc[
        candidate_lower == "over votes",
        "result_type"
    ] = "overvote"

    df.loc[
        candidate_lower == "under votes",
        "result_type"
    ] = "undervote"

    df.loc[
        df["result_type"].isin(
            ["overvote", "undervote"]
        ),
        "party"
    ] = pd.NA

    df = df[
        [
            "year",
            "county_name",
            "contest_type",
            "district_number",
            "contest_title",
            "result_type",
            "party",
            "candidate",
            "total_votes",
            "source_file",
        ]
    ].copy()

    result_order = {
        "candidate": 1,
        "write_in": 2,
        "overvote": 3,
        "undervote": 4,
    }

    df["_result_order"] = (
        df["result_type"]
        .map(result_order)
    )

    df = (
        df
        .sort_values(
            [
                "county_name",
                "contest_type",
                "district_number",
                "_result_order",
                "candidate",
            ],
            na_position="first"
        )
        .drop(
            columns="_result_order"
        )
        .reset_index(drop=True)
    )

    return df

**2020**

In [ ]:
election_2020_clean = (
    clean_combined_election_data(
        election_2020_combined_raw
    )
)

print(
    "2020 cleaned shape:",
    election_2020_clean.shape
)

print(
    "2020 counties:",
    election_2020_clean[
        "county_name"
    ].nunique()
)

print("\n2020 contest types:")
print(
    election_2020_clean[
        "contest_type"
    ].value_counts()
)

election_2020_clean.head(20)

**2024**

In [ ]:
election_2024_clean = (
    clean_combined_election_data(
        election_2024_combined_raw
    )
)

print(
    "2024 cleaned shape:",
    election_2024_clean.shape
)

print(
    "2024 counties:",
    election_2024_clean[
        "county_name"
    ].nunique()
)

print("\n2024 contest types:")
print(
    election_2024_clean[
        "contest_type"
    ].value_counts()
)

election_2024_clean.head(20)



---

**CHECKING**

In [ ]:
required_final_columns = [
    "year",
    "county_name",
    "contest_type",
    "contest_title",
    "result_type",
    "candidate",
    "total_votes",
    "source_file",
]

print("2020 missing required values:")

print(
    election_2020_clean[
        required_final_columns
    ].isna().sum()
)

print("\n2024 missing required values:")

print(
    election_2024_clean[
        required_final_columns
    ].isna().sum()
)

In [ ]:
negative_votes_2020 = (
    election_2020_clean[
        election_2020_clean[
            "total_votes"
        ] < 0
    ]
)

negative_votes_2024 = (
    election_2024_clean[
        election_2024_clean[
            "total_votes"
        ] < 0
    ]
)

print(
    "2020 negative vote rows:",
    len(negative_votes_2020)
)

print(
    "2024 negative vote rows:",
    len(negative_votes_2024)
)

In [ ]:
election_key_columns = [
    "year",
    "county_name",
    "contest_title",
    "result_type",
    "party",
    "candidate",
]

duplicates_2020 = election_2020_clean[
    election_2020_clean.duplicated(
        subset=election_key_columns,
        keep=False
    )
]

duplicates_2024 = election_2024_clean[
    election_2024_clean.duplicated(
        subset=election_key_columns,
        keep=False
    )
]

print(
    "2020 duplicate rows:",
    len(duplicates_2020)
)

print(
    "2024 duplicate rows:",
    len(duplicates_2024)
)



---

**CONTEST SUMMARY FUNCTION**


*   Creates one row per county contest that has canidate votes, overvotes, undervotes, and total participation

In [ ]:
def create_election_contest_summary(
    election_clean
):

    summary_source = (
        election_clean.copy()
    )

    summary_source[
        "candidate_votes"
    ] = summary_source[
        "total_votes"
    ].where(
        summary_source[
            "result_type"
        ].isin(
            ["candidate", "write_in"]
        ),
        0
    )

    summary_source[
        "overvotes"
    ] = summary_source[
        "total_votes"
    ].where(
        summary_source[
            "result_type"
        ] == "overvote",
        0
    )

    summary_source[
        "undervotes"
    ] = summary_source[
        "total_votes"
    ].where(
        summary_source[
            "result_type"
        ] == "undervote",
        0
    )

    summary = (
        summary_source
        .groupby(
            [
                "year",
                "county_name",
                "contest_type",
                "district_number",
                "contest_title",
            ],
            dropna=False,
            as_index=False
        )
        .agg(
            candidate_votes=(
                "candidate_votes",
                "sum"
            ),
            overvotes=(
                "overvotes",
                "sum"
            ),
            undervotes=(
                "undervotes",
                "sum"
            ),
            contest_ballots=(
                "total_votes",
                "sum"
            ),
        )
    )

    numeric_columns = [
        "candidate_votes",
        "overvotes",
        "undervotes",
        "contest_ballots",
    ]

    for column in numeric_columns:
        summary[column] = (
            summary[column]
            .astype("Int64")
        )

    return (
        summary
        .sort_values(
            [
                "year",
                "county_name",
                "contest_type",
                "district_number",
            ],
            na_position="first"
        )
        .reset_index(drop=True)
    )

In [ ]:
election_summary_2020 = (
    create_election_contest_summary(
        election_2020_clean
    )
)

election_summary_2024 = (
    create_election_contest_summary(
        election_2024_clean
    )
)

print(
    "2020 summary shape:",
    election_summary_2020.shape
)

print(
    "2024 summary shape:",
    election_summary_2024.shape
)

election_summary_2020.head(10)

This validates presidential totals against cast ballots

In [ ]:
def extract_county_ballot_totals(
    combined_raw
):

    df = combined_raw.copy()

    df["contest_title"] = clean_election_text(
        df["contest_title"]
    )

    df["candidate"] = clean_election_text(
        df["candidate"]
    )

    df["total_votes"] = pd.to_numeric(
        df["total_votes"],
        errors="coerce"
    ).round().astype("Int64")

    ballot_totals = df[
        df["contest_title"]
        == "BALLOTS CAST - TOTAL"
    ].copy()

    ballot_totals = ballot_totals[
        [
            "year",
            "county_name",
            "total_votes",
        ]
    ].rename(
        columns={
            "total_votes":
            "official_ballots_cast"
        }
    )

    return (
        ballot_totals
        .drop_duplicates(
            subset=[
                "year",
                "county_name",
            ]
        )
        .sort_values(
            [
                "year",
                "county_name",
            ]
        )
        .reset_index(drop=True)
    )

In [ ]:
ballot_totals_2020 = (
    extract_county_ballot_totals(
        election_2020_combined_raw
    )
)

ballot_totals_2024 = (
    extract_county_ballot_totals(
        election_2024_combined_raw
    )
)

print(
    "2020 ballot-total rows:",
    len(ballot_totals_2020)
)

print(
    "2024 ballot-total rows:",
    len(ballot_totals_2024)
)

In [ ]:
president_summary_2020 = (
    election_summary_2020[
        election_summary_2020[
            "contest_type"
        ] == "president"
    ][
        [
            "year",
            "county_name",
            "candidate_votes",
            "overvotes",
            "undervotes",
            "contest_ballots",
        ]
    ]
)

president_validation_2020 = (
    president_summary_2020
    .merge(
        ballot_totals_2020,
        on=[
            "year",
            "county_name",
        ],
        how="outer",
        validate="one_to_one"
    )
)

president_validation_2020[
    "difference"
] = (
    president_validation_2020[
        "contest_ballots"
    ]
    - president_validation_2020[
        "official_ballots_cast"
    ]
)

president_validation_2020

In [ ]:
president_summary_2024 = (
    election_summary_2024[
        election_summary_2024[
            "contest_type"
        ] == "president"
    ][
        [
            "year",
            "county_name",
            "candidate_votes",
            "overvotes",
            "undervotes",
            "contest_ballots",
        ]
    ]
)

president_validation_2024 = (
    president_summary_2024
    .merge(
        ballot_totals_2024,
        on=[
            "year",
            "county_name",
        ],
        how="outer",
        validate="one_to_one"
    )
)

president_validation_2024[
    "difference"
] = (
    president_validation_2024[
        "contest_ballots"
    ]
    - president_validation_2024[
        "official_ballots_cast"
    ]
)

president_validation_2024

In [ ]:
president_discrepancies_2020 = (
    president_validation_2020[
        president_validation_2020[
            "difference"
        ].fillna(0) != 0
    ]
)

president_discrepancies_2024 = (
    president_validation_2024[
        president_validation_2024[
            "difference"
        ].fillna(0) != 0
    ]
)

print(
    "2020 presidential discrepancies:",
    len(president_discrepancies_2020)
)

print(
    "2024 presidential discrepancies:",
    len(president_discrepancies_2024)
)

In [ ]:
election_results_clean = pd.concat(
    [
        election_2020_clean,
        election_2024_clean,
    ],
    ignore_index=True
)

election_results_clean = (
    election_results_clean
    .sort_values(
        [
            "year",
            "county_name",
            "contest_type",
            "district_number",
            "result_type",
            "candidate",
        ],
        na_position="first"
    )
    .reset_index(drop=True)
)

print(
    "Combined detailed shape:",
    election_results_clean.shape
)

print("\nCounties by year:")

print(
    election_results_clean
    .groupby("year")["county_name"]
    .nunique()
)

In [ ]:
election_summary_clean = pd.concat(
    [
        election_summary_2020,
        election_summary_2024,
    ],
    ignore_index=True
)

election_summary_clean = (
    election_summary_clean
    .sort_values(
        [
            "year",
            "county_name",
            "contest_type",
            "district_number",
        ],
        na_position="first"
    )
    .reset_index(drop=True)
)

print(
    "Combined summary shape:",
    election_summary_clean.shape
)

election_summary_clean.head()

In [ ]:
election_2020_output = (
    CLEAN_2020
    / "election_results_2020_clean.csv"
)

election_2024_output = (
    CLEAN_2024
    / "election_results_2024_clean.csv"
)

election_combined_output = (
    CLEAN_COMBINED
    / "election_results_clean.csv"
)

election_summary_2020_output = (
    CLEAN_2020
    / "election_contest_summary_2020_clean.csv"
)

election_summary_2024_output = (
    CLEAN_2024
    / "election_contest_summary_2024_clean.csv"
)

election_summary_combined_output = (
    CLEAN_COMBINED
    / "election_contest_summary_clean.csv"
)

In [ ]:
election_2020_clean.to_csv(
    election_2020_output,
    index=False,
    encoding="utf-8"
)

election_2024_clean.to_csv(
    election_2024_output,
    index=False,
    encoding="utf-8"
)

election_results_clean.to_csv(
    election_combined_output,
    index=False,
    encoding="utf-8"
)

print("Saved detailed election files:")
print(election_2020_output)
print(election_2024_output)
print(election_combined_output)

In [ ]:
election_summary_2020.to_csv(
    election_summary_2020_output,
    index=False,
    encoding="utf-8"
)

election_summary_2024.to_csv(
    election_summary_2024_output,
    index=False,
    encoding="utf-8"
)

election_summary_clean.to_csv(
    election_summary_combined_output,
    index=False,
    encoding="utf-8"
)

print("Saved contest-summary files:")
print(election_summary_2020_output)
print(election_summary_2024_output)
print(election_summary_combined_output)